### ISSUE TITLE
trait constructor calling convention

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1]
- switch calling convention from individual functions to impls of constructor traits in trans.rs, meas.rs, core.rs
- refactor trans.rs and meas.rs into folders
- split trans.rs code between mod.rs and dataframe.rs
- add num crate and remove OpenDPInto trait

**Comment by andrewvyrros** [comment]
The PR for this is under #2.

**Comment by Shoeboxam** [comment]
Closed in #2
