### ISSUE TITLE
Implement python optional dependency test matrix?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1037]
We want to know that our software will work in different environments: The first thing would be to run tests under different python version numbers.
- See #1036 

A subtler point is that we have a few places where we run different code depending on whether numpy is installed: `_convert.py`, `typing.py`, `test_convert.py`, `test_typing.py` all have:
```
try:
    import numpy
```
and `skipif('numpy' not in sys.modules)` is also used in the tests. I'm not seeing anything in the docs that explains what numpy gives us as an optional install. If we want to be confident that it works both ways, we should probably test it.

**Comment by Shoeboxam** [comment]
The PCA PR adds numpy to the CI dependencies, and numpy as purely additive, so just testing with numpy should be sufficient-- no need to add another axis.

**Comment by mccalluc** [comment]
Sounds good. Then this can be closed.

**Comment by Shoeboxam** [comment]
I see now how having an optional dependency on numpy/scikit/scipy etc for pytests would be useful, just to ensure the library still loads without them. Sorry for the wrong direction here!
