### ISSUE TITLE
R: Basic Documentation

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1041]
- Add basic R documentation including notebooks
- Needs further definition and consideration of future Polars build

**Comment by mccalluc** [comment]
We definitely do need R documentation and examples, but we'll be doing it in tabs parallel to the Python documentation. One place to begin is:
- #1291

We do not plan to use R vignettes (and we'll probably be moving away from Python notebooks, too). Once the parallel tab documentation is in place we should see if there's anything in `vignettes_old` that isn't covered elsewhere, and then delete that directory.
- #1258

Closing this issue as duplicate.
