### ISSUE TITLE
Use new source instead of teacher data

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1076]
6/24/24 - renamed issue
---
Can we say where the teacher data comes from? Is it synthetic data? It feels a little weird to say simple anonymization is not sufficient... and then go head and appear to rely on just dropping the state column.

Close when we can add a little note about the provenance of this data to the new tutorial.

**Comment by raprasad** [comment]
(Note sent to data preparer. If not answered soon, will move this issue out of the milestone)

**Comment by raprasad** [comment]
> The data file was taken from this source: [http://spss.allenandunwin.com.s3-website-ap-southeast-2.amazonaws.com/data-files.html](https://urldefense.proofpoint.com/v2/url?u=http-3A__spss.allenandunwin.com.s3-2Dwebsite-2Dap-2Dsoutheast-2D2.amazonaws.com_data-2Dfiles.html&d=DwMGaQ&c=WO-RGvefibhHBZq3fL85hQ&r=EkFi6BF7pof1mvmoyqcphtSeruEfuDmHCUNhyy4Y_XM&m=PpHbhkuOLDrIuGDPkz0mqGrPB6O8ewCd9uITbAsdCbOMGNptpENJCdzOdP-vsefj&s=1gTE5aMAYJrKRbRljnvX3ys9QiYiJTSLg5GlGUFH3XY&e=) (the first database, survey.sav). Nonetheless, as it had few entries, we repeated the data to reach 7000 entries. Also, we made a different story as follows about the participants in the survey and its purpose:

**Comment by mccalluc** [comment]
Thanks for tracking this down: Feel free to assign to me to make the edit, otherwise I'll leave it to you. Perhaps something like:

> This sample data is derived from a survey in [Julie Pallant's SPSS Survival Manual](https://www.taylorfrancis.com/books/mono/10.4324/9781003117452/spss-survival-manual-julie-pallant)

If you want more to worry about:
- Do we have a license for this? Should we?
- It feels weird to just duplicate the data to get to an acceptable error level, and neither explaining our process nor hoping it won't be noticed feels great. -- It's one thing that people should definitely *not* do in the real world.

**Comment by raprasad** [comment]
^ Yes. Agreed. Can't use w/o a license
