### ISSUE TITLE
Remove vestigial `@versioned` decorator

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1145]
- From #1144 
> `@proven` is vestigial, but hasn't been removed yet. We've made updates that makes this un-necessary, but a careful, close look is necessary to extricate this.

**Comment by mccalluc** [comment]
Change in direction: This could be useful if we want to have a proof for extrinsic python code. It's unused now, but let's keep it around.

**Comment by mccalluc** [comment]
Looks like it's not on generated code now:
```
cd python/src; grep proven -r .
./opendp/extrinsics/_test.py:    from opendp._lib import proven
./opendp/extrinsics/_test.py:    @proven
./opendp/extrinsics/_test.py:        """A dummy function for testing the proven decorator.
./opendp/_lib.py:def proven(function):
```

Not currently used, but could be used on extrinsics in the future. Closing.

**Comment by Shoeboxam** [comment]
I think something is off in your grep? 
https://github.com/opendp/opendp/blob/main/python/src/opendp/accuracy.py#L22

**Comment by Shoeboxam** [comment]
I'm sorry, it's `@versioned` that is vestigial.
