### ISSUE TITLE
Stability Mechanism -- Implementation

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#116]
- [x] Implement function
- [x] Include comments
- [x] Write tests

(The title of this is not great, not sure what to call it. This is for `make_base_stability()`, the Measurement that calculates noisy counts via stability.)

**Comment by andrewvyrros** [comment]
Issue for proof is in #117.

**Comment by Shoeboxam** [comment]
The measurement itself is implemented. The output is a HashMap<K, C>, where K is the released category and C the noisy count for that category. We need to have a way to return hashmaps over FFI.

**Comment by andrewvyrros** [comment]
In the interest of granularity, let's call this done. I've opened #125 for the HashMap data loader.
