### ISSUE TITLE
Link locally generated Rust docs into sphinx structure?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1160]
This goes back several years, to PR #300 -- https://github.com/opendp/opendp/blame/008b0e20356f49ff358eb58c69f9aff2a512b788/docs/Makefile#L32

> ```
> 	# TODO: Figure out how to link locally generated Rust docs into sphinx structure.
> ```

Does it still make sense to try to have the rust documentation inside the sphinx directory? Or are we happy linking to docs.rs? Possible advantages of rust docs inside the sphinx output directory:
- Relative links in and out of rust docs.
- Link checking against all docs.
- Possibly, text search across all docs.

Might get a better sense of whether this is a good or bad idea if I actually try to implement it... but feel free to comment.

**Comment by Shoeboxam** [comment]
We're going to have docs.rs docs regardless, as those always get built and hosted by the Rust folks. So I'm pretty sure there would be two sets of docs.

# Negatives
* may be confusing to have two sets of docs, and to have two sets of results come up in web searches
* may be confusing to get rust results mixed in when you search what are ostensibly python docs

# Positives
* as you mentioned
* our version could have private APIs included, and docs.rs doesn't, so our version of the docs would act as a proof index and the rust docs for general use


I think I'm more in favor of not hosting a second version of the docs. Open to opinions as always!

**Comment by mccalluc** [comment]
Doing nothing is easier! I'll clear the TODO. One question:

> our version could have private APIs included, and docs.rs doesn't, so our version of the docs would act as a proof index and the rust docs for general use

Oh: I was interpreting the local build as a preview of the docs.rs build, but that's not really the case: It really serves as documentation for internal developers. So if we have a proof of a private function, it will only be rendered locally -- This surprises me a little, but if this is what we want, great!

**Comment by Shoeboxam** [comment]
I like having proof docs on internal functions accessible to people outside the library, which is the argument for making private functions visible in public documentation. However, it comes at the risk of confusing developers. Regardless, I'm still in favor of keeping private functions visible.

**Comment by mccalluc** [comment]
More notes from Michael:

> - I'm a little concerned of hosting a second version of the rust docs, and then there being two sets of the same docs being indexed on google as well as two identical docs websites.
> - I think global text search is not very useful, as people probably wouldn't like getting results from a mixture of languages. The results should be in the same language, and possibly link back to Rust.
> - We could still do link checking [on rust docs separately](https://github.com/deadlinks/cargo-deadlinks). The major downside is that the sphinx link checker will give false positives when links from sphinx are made to brand new rust functions.

Will go forward with removing TODOs.

**Comment by mccalluc** [comment]
We decided the original idea on this issue is not the direction we want to go, and the TODO cleanup is done (#1186), so this can be closed.
