### ISSUE TITLE
Mention R install at top of development-environment.html

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1223]
My sense is that R should be considered a peer of Python, and should also be installed by developers? There is an "R Setup" section, but it doesn't mention installing R itself, or whether there is a minimum version requirement.

**Comment by Shoeboxam** [comment]
I think in general we shouldn't require contributors to set up every bindings language? For people like us, sure, but drive-by contributors don't need all.

**Comment by mccalluc** [comment]
sounds good! Down the road, if there were R UDFs, possible that a user might just be working with rust and R? But that's down the road. Closing.

**Comment by Shoeboxam** [comment]
Yeah, we could relax the install requirements by moving Python down into the Python section.
Also add R to the R section.
