### ISSUE TITLE
Explain the extra brew installs for R on macOS

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1238]
```
brew install harfbuzz fribidi libgit2 xquartz
```

Suggest adding a `<details>` section that explains these: Are they needed for R in general, or is it something particular about opendp? I know that xquartz is needed with the standard R install, because that install also includes tcltk stuff, so X11 compatibility is not surprising, but not sure about the others.

**Comment by Shoeboxam** [comment]
They are all for devtools, which is developer tooling only. The package itself only has a soft dependency on jsonlite.
