### ISSUE TITLE
R warning: "needs @export or @exportS3method tag"

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1251]
`Rscript -e 'devtools::document()'` is working, but early in the log there are a pair of warnings:

```
ℹ Updating opendp documentation
ℹ Loading opendp
Registered S3 method overwritten by 'opendp':
  method        from
  print.hashtab utils
✖ mod.R:390: S3 method `to_str.default` needs @export or @exportS3method tag.
✖ mod.R:391: S3 method `to_str.hashtab` needs @export or @exportS3method tag.
```

[Same warning in CI](https://github.com/opendp/opendp/actions/runs/7903643328/job/21572262951?pr=1250#step:7:12)

The build still works, so not critical, but it would be good not to have warnings in the log.

**Comment by Shoeboxam** [comment]
Fixed in #2082
