### ISSUE TITLE
Clarify direction on vignettes

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1254]
See also:
- #893 (Currently in `vignettes_old`: Not sure what needs to be updated.)
- #1233 

Should we work on R examples that parallel the python, rather than focusing on stand-alone vignettes?

Or would some vignettes still be useful, even if the main goal is to present the APIs in parallel?

**Comment by Shoeboxam** [comment]
Now that we have an approach for embedding test-able R examples in multi-tabs, I think it would be better to consolidate on multi-tabs throughout. Vignettes will have the same tradeoff as embedded notebooks, in that they only support one language, and the text will have to be duplicated. This makes me dislike having a lot of our documentation in notebooks, and I'm hesitant to commit to doing the same in R for vignettes. I also don't like the vignette editing experience with the mixed pseudo-latex formatting.

**Comment by mccalluc** [comment]
Great -- Just filed #1258 for the follow-up work. Since the direction is clear, this can be closed.
