### ISSUE TITLE
Remove `vignettes_old`; expand tab examples

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1258]
- With #1233 we will have the machinery for tested documentation examples.
- We concluded in #1254 that we don't want to invest time in R vignettes as a form of documentation.

So we should remove the `R/opendp/vignettes_old` directory, and have at least that much added as examples in the docs.

**Comment by Shoeboxam** [comment]
I agree with this direction! Tabs in sphinx are better.
