### ISSUE TITLE
Dataframe Transformations -- Implementation

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#127]
We already have a bunch of dataframe constructors (`make_split_dataframe()`, `make_parse_column()`, etc.).

Opening this as a placeholder, so we can make an explicit decision if we need more or we're good.

**Comment by andrewvyrros** [comment]
Issue for proofs: #128.

**Comment by Shoeboxam** [comment]
This is too broadly scoped, and can never be closed. We should open smaller issues for more specific dataframe transformations on an as-needed basis.
