### ISSUE TITLE
doc consistency: `import opendp.prelude as dp` vs `from opendp.mod import enable_features`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1275]
Is there any reason to reference `opendp.mod` in the docs, or should we consistently steer users to the `prelude`? The synonymous imports could be confusing to users.

**Comment by Shoeboxam** [comment]
We should always direct towards the prelude.

**Comment by mccalluc** [comment]
I think think this resolved, largely thanks to
- #1442

Closing.
