### ISSUE TITLE
.gitignore latex by-products and pdf

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1333]
If we don't want these in the repo, we should ignore them!

**Comment by abigail-gentle** [comment]
That would help a lot  😅 I had them in my own gitignore but lost the changes when I pulled, sorry!

**Comment by Shoeboxam** [comment]
No need to be sorry! No harm done, and it's a gap in our tooling anyways. :P

**Comment by abigail-gentle** [comment]
Added a pull review, none of the file extensions overlap with existing files, but I can't guarantee the list is complete. File extensions came from my own tex editor + [this stackoverflow](https://tex.stackexchange.com/questions/597675/understanding-all-output-files-when-compiling-a-latex-document)
