### ISSUE TITLE
Consistency in capitalization of Laplace and Gaussian

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1335]
Do we have a style guide on this? I think there's some variation. My sense is that "Laplace" and "Gaussian" should both be capitalized standing alone, but perhaps not if they aren't a free standing word -- but not confident about this. File a very low priority issue?

_Originally posted by @mccalluc in https://github.com/opendp/opendp/pull/1318#discussion_r1504786437_

**Comment by SalilVadhan** [comment]
The inconsistency has to do with them being based on proper names (Laplace, Gauss), but over time these things tend to get uncapitalized (cf. "joules").  I don't feel strongly about it.
