### ISSUE TITLE
Windows build with system libs

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#137]
We have a workaround to build on Windows (#100), but this disables MPFR and OpenSSL. We need to figure out a solution that includes everything.

**Comment by Shoeboxam** [comment]
This is the document from Joshua at Microsoft with build instructions for openssl and gmp/mpfr for windows.

https://docs.google.com/document/d/1tpYr5bFtFcl4Amz0qWMBmXpcVajPN7yYXy4rKNz2wnY/edit
