### ISSUE TITLE
Sphinx does not document special methods by default

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1394]
I was looking for the docs we have on `Context.__init__`, and couldn't find them in the rendered documentation. Turns out, Sphinx does not render docs for "special" methods, including the constructor, by default. A couple different routes to resolving this:

- (A) Move any `__init__` docs up to the class level. [Example in sphinx docs](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html)
- (B) Alternatively, tell sphinx we want to document special methods, too. [SO](https://stackoverflow.com/questions/5599254)
- (A+B) Or both: I think documenting constructor params at the top makes a lot of sense... but if we've got any special behavior on magic methods, we could document them, too.

I would lean towards just (A).

**Comment by Shoeboxam** [comment]
Agree with (A). Nice catch!
