### ISSUE TITLE
Wordsmithing of type and function names

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#141]
Grab bag issue for tracking various names we'd like to improve. Add more as we come across them:

- [ ] LpSensitivity -> LpDistance
- [ ] SymmetricDistance -> SymmetricDifference (see also #142)
- [ ] HammingDistance -> SubstituteDistance

**Comment by Shoeboxam** [comment]
I'm not a big fan of renaming SymmetricDistance to SymmetricDifference. I think of SymmetricDifference as the set of different items and SymmetricDistance the size of that set.
