### ISSUE TITLE
Polars MVP documentation

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1410]
Include examples of using Polars for sums, means, groupby, and quantiles

**Comment by raprasad** [comment]
(depending on time, this may move to the next, smaller release)

**Comment by mccalluc** [comment]
In the API docs, `rust/src/measurements/code/make_private_lazyframe.rst` already has sums and groupby, adding mean wouldn't be hard, and with a data set this trivial, median might be sufficient to demonstrate quantiles?

**Comment by raprasad** [comment]
closing in favor of multiple notebook issues
