### ISSUE TITLE
Python job fails on nightly: Missing `setuptools`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1413]
Nightly is failing. [setuptools is missing](https://github.com/opendp/opendp/actions/runs/8369403837/job/22915415668#step:6:38):
```
Build bdist
$ (cd python && python setup.py bdist_wheel -d wheelhouse)
Traceback (most recent call last):
  File "/home/runner/work/opendp/opendp/python/setup.py", line 1, in <module>
    from setuptools import setup  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'setuptools'
Error: Process completed with exit code 1.
```

Easy fix?

Also, consider adding a nightly status badge on the README so this will be a higher priority for us going forward.

**Comment by Shoeboxam** [comment]
https://github.com/opendp/opendp/actions/runs/8385185309/job/22964268691

I think we still need to add the pip install.
