### ISSUE TITLE
docs.rs builds failing

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1414]
https://docs.rs/crate/opendp/0.9.2-nightly.20240314.1:

> docs.rs failed to build opendp-0.9.2-nightly.20240314.1
> Please check the [build logs](https://docs.rs/crate/opendp/0.9.2-nightly.20240314.1/builds) for more information.
> See [Builds](https://docs.rs/about/builds) for ideas on how to fix a failed build, or [Metadata](https://docs.rs/about/metadata) for how to configure docs.rs builds.
> If you believe this is docs.rs' fault, [open an issue](https://github.com/rust-lang/docs.rs/issues/new/choose).
> Visit the last successful build: opendp-0.9.0-nightly.20240131.1

Looking at the [log](https://docs.rs/crate/opendp/0.9.2/builds/1120302):

```
[INFO] running `Command { std: "docker" "start" "-a" "8ae8bda3af16bcc3d43a4dbd7cae80ecaa2f8df519d3c1b46653fd90be21c0a4", kill_on_drop: false }`
[INFO] [stderr] warning: target filter specified, but no targets matched; this is a no-op
[INFO] [stderr]    Compiling opendp v0.9.2 (/opt/rustwide/workdir)
[INFO] [stderr] error: failed to run custom build command for `opendp v0.9.2 (/opt/rustwide/workdir)`
[INFO] [stderr] 
[INFO] [stderr] Caused by:
[INFO] [stderr]   process didn't exit successfully: `/opt/rustwide/target/debug/build/opendp-7e653207d04b3d6f/build-script-main` (exit status: 101)
[INFO] [stderr]   --- stdout
[INFO] [stderr]   cargo:rerun-if-env-changed=OPENDP_SPHINX_PORT
[INFO] [stderr]   cargo:rerun-if-env-changed=OPENDP_RUSTDOC_PORT
[INFO] [stderr]   cargo:rerun-if-env-changed=OPENDP_REMOTE_SPHINX_URI
[INFO] [stderr]   cargo:rerun-if-env-changed=OPENDP_REMOTE_RUSTDOC_URI
[INFO] [stderr] 
[INFO] [stderr]   --- stderr
[INFO] [stderr]   thread 'main' panicked at /opt/rustwide/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/cbindgen-0.20.0/src/bindgen/bindings.rs:101:43:
[INFO] [stderr]   called `Result::unwrap()` on an `Err` value: Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }
```

My sense is that the `Read-only file system` error is a red herring: It also shows up in [this report](https://github.com/rust-skia/rust-skia/issues/720#issuecomment-1307687183), where the real problem was unrelated.

There are [instructions for emulating the doc.rs build](https://github.com/rust-lang/docs.rs/blob/master/README.md#build-subcommand)... but if we have any intuition about what's going wrong, it'd be good to try that before going too deep.

**Comment by mccalluc** [comment]
Changed my mind: Not a red herring.

https://docs.rs/about/builds#read-only-directories
> ## Write attempt on read-only directories
> 
> Most of the sandbox is a read-only file system, including the source directory of your crate and its dependencies. If your build.rs generates files that are relevant for documentation, consider writing to the [cargo output directory](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates), passed in the environment variable OUT_DIR.

Do we write to the source directory of the crate? Yes we do, in `generate_header()`, which creates `opendp.h`

When was it introduced?
```
6ce2362cd (Michael Shoemate 2024-02-01 12:44:42 -0500  49) fn generate_header() {
```
that's the [R bindings PR](https://github.com/opendp/opendp/pull/679).

What is the last successful docs.rs build?
> Visit the last successful build: opendp-0.9.0-nightly.20240131.1 

ie, the day before.

- Can this output file be moved over to the R directory?
- Is there a code or process change that would help us catch docs.rs problems earlier?
- See also #1430

**Comment by Shoeboxam** [comment]
The fix here is to just adjust the `#[cfg(feature = "ffi")]` to `#[cfg(feature = "bindings")]` (as well as the cfg guard on the function it decorates). 

Explanation: All code-gen should be behind `bindings`, because `Cargo.toml` enables `ffi` for docs.rs builds.
