### ISSUE TITLE
Usability: API Design Mirroring Popular Libraries 

### ISSUE THREAD

**Issue by chikeabuah** [opendp/opendp#1419]
<img width="425" alt="Screen Shot 2024-03-21 at 9 43 28 AM" src="https://github.com/opendp/opendp/assets/2280440/ed552376-2a80-472c-b455-dcbcd92f04a5">

Consider leveraging the design of popular data science libraries in OpenDP API design for a learning scaffold.

From study "Evaluating the Usability of Differential Privacy Tools with Data Practitioners" by Ngong et al.

**Comment by chikeabuah** [comment]
<img width="322" alt="Screen Shot 2024-03-21 at 9 46 47 AM" src="https://github.com/opendp/opendp/assets/2280440/b962a205-7b7b-46b8-9e58-46ae42d9615f">

**Comment by chikeabuah** [comment]
<img width="321" alt="Screen Shot 2024-03-21 at 9 45 18 AM" src="https://github.com/opendp/opendp/assets/2280440/54074da1-708e-4702-a604-a8dc19462cad">

**Comment by Shoeboxam** [comment]
There's three changes to the library that touch on this:

. Context API, which helps to hide the mechanics of composition and gives a shortened dot-chaining query syntax (released around the time of this paper) 
. PCA mimics sklearn, and I'd like to expose more models in this way (released Q1 2024)
. Polars directly uses the Polars API, without any mimicry (upcoming)

We should continue our current approach of doing core development directly in the framework API, and then generating framework API bindings in other languages. Additional wrapper APIs, like those mentioned above, should be built on top that mimic the patterns people are used to in the various languages and popular libraries out there.
