### ISSUE TITLE
YAML anchors to reduce copy and paste in workflows?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1431]
We have many steps that are repeated across workflow jobs: checkout, binding download, python setup.

Generally, getting rid of repetition is a good thing: We might use YAML anchors, so these only need to be specified once per file.

But, it's possible to trip over the syntax, and in some ways it does make it more complex. We don't want to spend time just getting the YAML to parse.

Thoughts?

**Comment by Shoeboxam** [comment]
I like this idea, but it's a shame we can't de-dupe across all files. Seems like that limitation reduces the benefits.

Also, it seems like GA disables anchors: https://github.com/actions/runner/issues/1182

**Comment by mccalluc** [comment]
> Also, it seems like GA disables anchors: https://github.com/actions/runner/issues/1182

Oh, that's a big roadblock. Between it being impossible, and not a huge win even if it were possible, makes sense to close. Sorry for the noise.
