### ISSUE TITLE
document `pip install opendp[numpy]` and `pip install opendp[scikit-learn]`?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1432]
I could be overlooking it, but I don't think we mention these extra requires anywhere in our docs.

I think the right place is in the API reference, and we'd probably just add a note for each method that needs extra installs, either:
> This method requires extra installs: `pip install opendp[numpy]`

or 
> This method requires extra installs: `pip install opendp[scikit-learn]`

I also worry that people might be tempted to just `pip install numpy` -- Would it make any sense to rename our extras to reflect functionality, rather than libraries? something like: `pip install opendp[pca]`

**Comment by Shoeboxam** [comment]
I anticipate adding more models that mimic the sklearn API, so naming the feature `pca` will be too narrow.

Do you think documenting extra installs is still necessary when we already have error messages?

**Comment by mccalluc** [comment]
> I anticipate adding more models that mimic the sklearn API, so naming the feature pca will be too narrow.

ok, keeping the names. I don't have any better alternatives.

> Do you think documenting extra installs is still necessary when we also have error messages? If so, I'm fine with adding a note in the documentation.

Friendly error messages are nice, but I don't think users should need to rely on them. Ideally, if I'm following the directions, I should have any errors. Not sure where all the references are, but taking pca.ipynb, I'm thinking just a short note at the top.

**Comment by mccalluc** [comment]
@Shoeboxam , follow-up question: We don't have API docs for any of the extrinsics, presumably because the name is `_extrinsics`. Instead, we import these names in the prelude:
```
from opendp._extrinsics import sklearn, np_array2_domain
```

How would you feel about:
- Removing the underscore, so we'll get sphinx API docs?
- In prelude, `import *` just like we do for other modules?
- Making names under extrinsics private, if needed?

**Comment by mccalluc** [comment]
Mike is thinking making it public will work, and we also change `register_measurement`: instead of putting the argument into a different module, it will update the `constructors` in `context.py`:
```
constructors = {}
for module_name in ["transformations", "measurements"]:
```
