### ISSUE TITLE
`split_by_weights` fails in `Context.compositor`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1451]
- Spin-off from #1443

This test is failing, but it should pass:
```python
@pytest.mark.xfail
def test_split_by_weights():
    dp.Context.compositor(
        data=[1, 2, 3],
        privacy_unit=dp.unit_of(contributions=1),
        privacy_loss=dp.loss_of(epsilon=3.0, delta=1e-6),
        split_by_weights=[1, 2], # Bug: split_evenly_over works, but this doesn't.
        domain=dp.vector_domain(dp.atom_domain(T=int)),
    )
```

**Comment by Shoeboxam** [comment]
I think the key adjustment is:

```python
    elif split_by_weights is not None: # pragma: no cover
        weights = [mul(d_out, w) for w in split_by_weights]
```

**Comment by mccalluc** [comment]
Reopen

> I merged the split_by_weights PR a bit too quickly, and something seems fishy.
> https://github.com/opendp/opendp/pull/1456/files#diff-9849b8e219cf0cbdca7426bfb254cd3b9951e3fe6d16714806fc5cec1a08114aR697
> If d_out is (1., 1e-6), then wouldn't weights then be (1., 1e-6, 1., 1e-6)? Ideally it would scale the numbers inside, as mentioned in this comment:
> https://github.com/opendp/opendp/issues/1451#issuecomment-2028239297

**Comment by Shoeboxam** [comment]
The test if no longer ignored.
