### ISSUE TITLE
Context API Improvement: Better message if domain is incorrect

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1470]
from @mccalluc 

## Problem

Reference:
  - https://github.com/opendp/opendp/pull/1465/files#diff-d4d89fbd8d4c766e30502bed20068b70616b587d73d472f6eabb6da6967bfb03R72
  
  ```Python
@pytest.mark.xfail(raises=TypeError)
def test_scalar_instead_of_vector():
    # Currently fails with:
    #   TypeError: inferred type is Vec<i32>, expected i32. See https://github.com/opendp/opendp/discussions/298
    # Possible resolution:
    #   Would the domain ever not be a Vector? Maybe we check first for that, and give a more precise error.
    context = dp.Context.compositor(
        data=[1, 2, 3, 4, 5],
        privacy_unit=dp.unit_of(contributions=1),
        privacy_loss=dp.loss_of(epsilon=1.0),
        split_evenly_over=1,
        domain=dp.domain_of(int),
    )
    sum_query = context.query().clamp((1, 10)).sum()
    sum_query.laplace()
  ```
  
## Possible resolution:
- [ ] Better error handling
- [ ] Update test referenced above

**Comment by Shoeboxam** [comment]
In response to the comment, the domain could realistically contain many things:
* vector
* hashmap (as in PTR thresholding) or other data structures like trees or graphs
* scalar, boolean (local-DP rr) or string (like a csv literal)
* path
* queryable or stream
* database connection
* dataframe or series
* bit-vector or bytestring (think RAPPOR/local-DP)

**Comment by mccalluc** [comment]
Maybe zoom in on one particular mistake that's easy to make: Confusing
```
domain=dp.domain_of(int)
```
for
```
domain=dp.domain_of(list[int])
```
Before the catch-all error, we could look for this particular mistake and give a more precise error. We know that the fix is in `domain`, but there are a lot of parameters here, and the error message doesn't steer the user towards the line that needs to be fixed.

I'll draft something and we can look at it.
