### ISSUE TITLE
Identify Python API functions that would benefit from examples

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1489]
- Follow-up to #1439 

What functions are a priority for adding examples? I know that we're planning to deprecate and eventually remove a lot of the generated interface, but I don't have a clear sense of the scope. Within the set of functions that will remain, I'm not sure if some are a priority for adding examples.

This issue is resolved once the target functions have been identified: Could be a list here, or TODOs in the code, or something else. We can file a new issue for actually adding the examples.

**Comment by raprasad** [comment]
- Snippets for Python API documentation
- Which methods should there be examples for?
- Take typical workflow and prioritize for those methods.

**Comment by mccalluc** [comment]
Follow-ups filed. Closing.
