### ISSUE TITLE
`quickstart` and `typical-workflow` for Polars, for Python and R

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1491]
Before linking it into the docs, we could first focus on getting the files that we would include in place:
- [ ] `quickstart-polars.rst`
- [ ] `quickstart-polars.R`
- [ ] `typical-workflow-polars.rst`
- [ ] `typical-workflow-context.R`

Questions:
- When this comes online, would we drop the context examples, or are they still useful?
- My understanding is that the context API is still useful with Polars, and that Polars will also be available for R ... so the Python polars examples will use elements of context, and should be simpler than the R polars examples?
  - It might be tricky to explain why the thing we're calling the "Polars API" works differently in the two languages.

**Comment by raprasad** [comment]
@mccalluc : tension in having examples in only one version (e.g. Python) but not another (say R)

**Comment by mccalluc** [comment]
Clarifying the comment above: Right now we want two things that are in tension:
- Parallel tabbed documentation for Python and R
- Documentation that emphasizes idiomatic Python-only APIs

I'd suggest that for now the getting-started won't mention polars, and the later documentation won't mention R.

**Comment by mccalluc** [comment]
Following-up on the previous comment: We don't plan to have Polars for R anytime in the near future (and if/when we do, it will be obvious that the docs need updating) and for Python, we'll defer discussion of polars till the tabular data section.

So this issue can be closed without taking action.
