### ISSUE TITLE
Check the readability of error if wrong python polars is installed

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1501]
We might already have this covered, but we should make sure there's a readable error message if users have the wrong python polars version installed. 

- It would be easy for someone to just `pip install polars`, instead of installing our extra.
- If we don't have a high-level guard, the low-level rust error could be intimidating.

**Comment by Shoeboxam** [comment]
Error is here:
https://github.com/opendp/opendp/blob/7e5be5f897dac98cbaefb3f205489d715611309e/rust/src/data/ffi.rs#L213

**Comment by mccalluc** [comment]
Downgrading just the patch number didn't actually cause problems for me: Maybe the serialization hasn't changed with the last minor release, or maybe our testing doesn't exercise the serializations that have changed.

Downgrading to `polars==0.19` is too big of a change: the tests fail in the collection phase:
```
test/test_polars.py:23: in example_series
    pl.Series("C", ["1"] * 49 + [None], dtype=pl.String),
E   AttributeError: module 'polars' has no attribute 'String'
```
Trying to step through one test:
```
>>> val_in = pl.DataFrame({
...         "A": [1] * 100,
...         "B": ["X"] * 100,
...         "C": [True] * 100,
...     })
>>> obj = py_to_c(val_in, AnyObjectPtr, "DataFrame")
>>> val_out = c_to_py(obj)
>>> assert val_out.equals(val_in)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'DataFrame' object has no attribute 'equals'
```

At the start, I was thinking that because of version incompatibilities, it wouldn't work at all with mismatched versions, and I wondered if we should exit earlier with an error. But that doesn't seem to be the case: and it's probably better to let users get as far as they can, and only worrying about the serialization error message if it's actually a source of confusion. Closing.
