### ISSUE TITLE
Rename "UDF" to "plugins"

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1527]
... although, it looks like we don't actually say "UDF" or "user defined function" in the docs. Would these renamings make sense?
```diff
- user_domain
+ plugin_domain
- user_divergence
+ plugin_divergence
- user_transformation
+ plugin_transformation
```
etc.

- Prompted by #1508

**Comment by Shoeboxam** [comment]
No need to rename library functionality. This is more a change in how we talk about these features in blog posts, and how we will talk about these features in upcoming docs.

**Comment by mccalluc** [comment]
Great! Then there are just a couple of references to "UDF" in the codebase.
