### ISSUE TITLE
Count By (Categories) Known N -- Implementation

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#155]
I noticed that the HammingDistance implementation was really a restricted sensitivity proof for known N, and came up with a tighter sensitivity. There needs to be another set of constructors, or an optional arg, for count by and count by categories that take N and operate on sized domains.

**Comment by andrewvyrros** [comment]
Issue for proof: #158.

**Comment by Shoeboxam** [comment]
Initial implementation is in https://github.com/opendp/opendp/tree/155-sized-count-by
- Renamed `make_count_by` to `make_sized_count_by`
- Added a QI parameter to `make_base_geometric`. It defaults to i32.
- When you chain `sized_count_by_categories` with `make_base_geometric`, you have to specify `QI=float`

This has the same sensitivity as the unsized count by categories when distances are in L1 space. Since all other integer aggregators have integer sensitivities, I think I should not add QI to `base_geometric`, and not implement the sized counter for L1 spaces. It also doesn't make sense to open a PR for this until the discrete gaussian is implemented. We could cast the integer counts to floats and chain with the gaussian, but I'd rather not run continuous samplers on discrete data if we don't have to. Therefore this is blocked on #191.

**Comment by raprasad** [comment]
Will be closed by Polars work

**Comment by Shoeboxam** [comment]
Closed by #1540
