### ISSUE TITLE
R usability: Measurements w/o `arg` should error, instead of just returning NULL

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1555]
```
> gaussian <- make_gaussian(atom_domain(.T = f64), absolute_distance(.T = f64), scale = 1.0)
> gaussian(100.0)
> print(gaussian(100.0))
NULL
> gaussian(arg = 123.0)
[1] 123.2615
```
Translating from python to R I was stuck for a while because nothing was coming back.

Mike says:
> I think it would be better if an error were raised if the argument is not named. The reason why args are necessary is because they distinguish whether you're calling the function or map. I got feedback quite a few R experts that a more object-oriented API is not ideal

**Comment by Shoeboxam** [comment]
Should also verify similar checks exist on other library primitives.

**Comment by mccalluc** [comment]
The measurement functions returned by `make_*` and `then_*` seem to be different in this regard. 
```
> space <- c(atom_domain(.T = "i32"), absolute_distance(.T = "i32"))
> meas <- space |> then_laplace(1.)
> meas()
Error in meas() : expected exactly one of attr, arg or d_in
```
And some of the `make` functions already do work as desired:
```
> meas <- make_randomized_response_bool(0.75)
> meas()
Error in meas() : expected exactly one of attr, arg or d_in
```
First step might be to add tests of the behavior that is already what we want.
