### ISSUE TITLE
(6) Count (Statistic)

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#16]
- [x] Implement function
- [x] Include comments
- [x] Write tests

**Comment by andrewvyrros** [comment]
We have a decent implementation of this. One remaining issue is that it shouldn't use a raw `as` conversion.

**Comment by andrewvyrros** [comment]
This is just for the implementation of simple vector count (make_count()). This was completed in M1.

Histograms are in #65, stability-based calculation of the category set is in #116.

Issue for proof: #123.
