### ISSUE TITLE
CI fails because -Zscript now needs a hashbang

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1601]
I think the nightly chains now require the following to run?
```
#!/usr/bin/env -S cargo +nightly -Zscript
```

Not sure, but CI is failing:
https://github.com/opendp/opendp/actions/runs/9020660022/job/24786298591?pr=1597

**Comment by mccalluc** [comment]
For reference, the error begins with:
```
Run cargo +nightly -Zscript getting-started/code/quickstart-framework.rs
error: unknown start of token: `
 --> quickstart-framework.rs:2:1
  |
2 | ```cargo
  | ^^^
  |
  = note: character appears 2 more times
```

**Comment by mccalluc** [comment]
So my assumption is that something changed on nightly, but I haven't found a change log about it. The [example in the docs](https://doc.rust-lang.org/cargo/reference/unstable.html?highlight=Zscript#script) hasn't changed, but it fails the same way locally.

Some options:
- Get the existing script working. Next step might be to ask a question either on github or reddit. But nightly is going to be unstable, and maybe the lesson is not to rely on it.
- Can we pin to a particular nightly version? [Maybe](https://www.reddit.com/r/rust/comments/vnka0r/how_to_install_a_specific_nightly_version_but_as/), but seems involved.
- Or we can change this to a standalone mini cargo.toml. If we had lots of rust examples, that would be clutter, but for one, I think it's fine. (And if we had lots of rust examples, we'd also have the cost of compiling each one separately, so I don't think we're going that direction.)
