### ISSUE TITLE
Usability: differences in parsing string columns between pandas and `make_split_dataframe`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1606]
A user reported that the histograms on a column of strings was not working, while a histogram on a numeric column was fine. They were using `pandas.read_csv` and then `unique` to get the categories provided to `then_count_by_categories`.

It turns out that [`pandas.read_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) by default just splits on commas, while our `split_records` in Rust also strips leading whitespace on the resulting values. I'm not sure exactly where this happens, but we check this behavior in `test_make_split_records`:

```
    let arg = vec![
        "ant, foo".to_owned(),
        "bat, bar".to_owned(),
        "cat, baz".to_owned(),
    ];
    let ret = transformation.invoke(&arg).unwrap_test();
    assert_eq!(
        ret,
        vec![
            vec!["ant".to_owned(), "foo".to_owned()],
            vec!["bat".to_owned(), "bar".to_owned()],
            vec!["cat".to_owned(), "baz".to_owned()],
        ]
    );
```

I'd suggest we look at how Polars and the [python standard library csv parser](https://docs.python.org/3/library/csv.html) handle this, and if they all preserve whitespace, we should too.

**Comment by raprasad** [comment]
Quick note:

**Pandas**
  - `read_csv` _**removes**_ (eading + trailing whitespace from strings values by default .
  - To keep the whitespace, you can use update the `ignore_whitepace` parameter which defaults to True
  - `df = pl.read_csv("example.csv", ignore_whitespace=False)`

**Python `csv` module**
  - _**leaves**_ _leading_ whitepace by default
  - To remove _leading_ whitespace, you can set the parameter `skipinitialspace=True`
   ```Python
   with open('example.csv', newline='') as csvfile:
     # Create a reader with skipinitialspace enabled
     reader = csv.reader(csvfile, skipinitialspace=True)
   ```

**Comment by raprasad** [comment]
Adding this to the Polars Parity milestone but may switch depending on level of effort. 
Possible recommendation:
- Add `ignore_whitespace` parameter to library, similar to Polars where param applies to leading/trailing whitespace
- Default to `ignore_whitespace = False` if using `make_split_dataframe` directly
- If using Polars, use its properties, either by:
  - default to `ignore_whitespace = True`
  - pass `ignore_whitespace` value from Polars to OpenDP lib

**Comment by ltalirz** [comment]
I landed here via a Google search, so apologies for the off-topic question, but where do you see a `ignore_whitespace` parameter in polars?

It's neither in the docs [nor mentioned anywhere in the codebase](https://github.com/search?q=repo%3Apola-rs%2Fpolars%20ignore_whitespace&type=code)

**Comment by ltalirz** [comment]
It also appears that this

> **Polars**
> 
> * `read_csv` _**removes**_ (eading + trailing whitespace from strings values by default .

is not true since January https://github.com/pola-rs/polars/issues/10587

**Comment by mccalluc** [comment]
`make_split_dataframe` is being deprecated in favor of the Polars API, so we won't be investing any time here. Closing
