### ISSUE TITLE
Findability of proof documents

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1607]
It's not clear to me how a user would locate a proof pdf.
- Where should links to proofs appear? Sphinx / docs.rs / R docs?
- I would expect proofs to be findable with sphinx search, but https://docs.opendp.org/en/nightly/search.html?q=sample_discrete_gaussian returns no results, and in particular does not point to https://docs.opendp.org/en/nightly/proofs/rust/src/traits/samplers/cks20/sample_discrete_gaussian.pdf 

My sense right now is that there is no ready-to-go option for adding PDFs to the Sphinx index.
- indexing is part of the html build process, rather than a scan of the resulting documents.
- Formal documentation of search in sphinx is limited: [Is the web support even applicable to the JS index?](https://www.sphinx-doc.org/en/master/usage/advanced/websupport/searchadapters.html) / [RST markup to control indexing](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#index-generating-markup)
- Multiple threads suggest that no one really owns this: ["the only things I found was... reading the source code"](https://groups.google.com/g/sphinx-users/c/qtLQXDDHbYo) / ["there are no specialist for our search implementations"](https://github.com/sphinx-doc/sphinx/issues/776)

I know that there is some support for LaTeX in RST, and I also know that the LaTeX build is a little tricky to set up locally, and also adds some complexity in CI: Certainly not something to do impetuously, but could the proof sources be translated to RST?

**Comment by Shoeboxam** [comment]
The tooling adds links to proof documents into docstrings when possible. See the API documentation for make_count, for example.

**Comment by mccalluc** [comment]
I'm going to go ahead and close this:
- If someone is looking for a proof that doesn't correspond to a python method, they should look in the source. 
- If we ever did decide to reopen this, it's not impossible to update the index. Sphinx code to read and write the index is [here](https://github.com/sphinx-doc/sphinx/blob/v8.1.3/sphinx/search/__init__.py#L156), and if it were critical we could tokenize and index the proofs, but I think it would never be our top priority.
