### ISSUE TITLE
Add tags so links from CHANGELOG will work

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1628]
None of these links work -- though the links do work for older versions. Besides fixing these, Is there a problem with our release process, or did we not follow it?

> ## [0.9.2-dev](https://github.com/opendp/opendp/compare/v0.9.1...HEAD) - TBD
> 
> ## [0.9.1](https://github.com/opendp/opendp/compare/v0.9.0...v0.9.1) - 2024-02-07
> 
> ## [0.9.0](https://github.com/opendp/opendp/compare/v0.8.0...v0.9.0) - 2024-02-07

**Comment by Shoeboxam** [comment]
These tags were not pushed because of failures in the release process that would have otherwise pushed them.
