### ISSUE TITLE
v0.10 Release Announcement for Blog 

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1642]
Previous blog release notes: 
- https://drive.google.com/drive/folders/1rOR1-xPxjXfzQKE4yLlVUCa0DlCZjYNP

**Comment by mccalluc** [comment]
I've [posted a draft](https://docs.google.com/document/d/1A6fpOO0EK5lapzwMG_UWNp2pgcwkngxV4iOXzs8p248/edit).

I think the next step is to address nightly, and publish the new docs, and then update the links in this document.

**Comment by mccalluc** [comment]
In Sharon's court. Can close.
