### ISSUE TITLE
Flag (and explain?) `honest-but-curious` (and `contrib`?) in API docs

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1662]
Right now, there is no indication in the generated docs that that a particular method requires `contrib` or `honest-but-curious`. The semantics on `contrib` are clear enough, but for `honest-but-curious` an explanation of _why_ might be useful.

Without making things too complicated, we would like any additional info to be in both the R and Python docs.

Not sure right now what the implementation looks like, but it might be a convention we'll hold ourselves too, plus a test on the content of the docstrings.

_Originally posted by @mccalluc in https://github.com/opendp/opendp/pull/1602#discussion_r1626445775_

**Comment by Shoeboxam** [comment]
Closed in #1850

**Comment by mccalluc** [comment]
Reopening:
- #1850 -> #1931

are something a little different in my view. For this issue, I was hoping we could check every method and make sure the features required for use are expressed in the docs. 

- Users shouldn't need to run their code and see errors to know what features need to be enabled: Should be documented.
- I think this also ties to the larger conversation about proof writing. Right now if a proof is contributed, it isn't really obvious for the docs that a given method is extra solid.
- Implementation: Probably inject into the docstring, based on the feature flags?
