### ISSUE TITLE
Library users need to ignore typing on `release()` after `group_by`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1685]
```python
context.query()
.group_by("B")
.agg(pl.len().dp.noise(), pl.col("A").fill_null(2).dp.sum((0, 3)))
.release()  # type: ignore[union-attr]
```

> If our users would also need to add typing ignores like this, that's not ideal. Not something to block this PR, but perhaps file an issue unless there's an easy fix?

> It isn't ideal, and is unfortunately not an easy fix. The reason why the typing generally works out so nicely is because most of the LazyFrame APIs return `Self`, which, when subclassed, is `LazyFrameQuery`. However `.group_by` returns `LazyGroupBy`, which exits our subclass.

_Originally posted by @Shoeboxam in https://github.com/opendp/opendp/pull/1604#discussion_r1641870822_

**Comment by Shoeboxam** [comment]
Closed in #1713
