### ISSUE TITLE
specify minimum Rust version

### ISSUE THREAD

**Issue by pdurbin** [opendp/opendp#169]
On 7550cab I was seeing errors with `cargo build`

```
$ cargo build
   Compiling opendp-ffi v0.1.0 (/Users/pdurbin/github/opendp/opendp/rust/opendp-ffi)
   Compiling opendp v0.1.0 (/Users/pdurbin/github/opendp/opendp/rust/opendp)
error[E0391]: cycle detected when computing the bounds for type parameter `MO`
  --> opendp/src/trans/count.rs:53:31
   |
53 |     where MO: CountByConstant<MO::Distance> + SensitivityMetric,
   |                               ^^^^^^^^^^^^
   |
   = note: ...which again requires computing the bounds for type parameter `MO`, completing the cycle
note: cycle used when computing explicit predicates of `trans::count::make_count_by_categories`
  --> opendp/src/trans/count.rs:53:31
   |
53 |     where MO: CountByConstant<MO::Distance> + SensitivityMetric,
   |                               ^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
error: could not compile `opendp`

To learn more, run the command again with --verbose.
```

@Shoeboxam helped me figure out that my version of Rust was too old. Using `rustup update` I upgraded from Rust 1.51.0 to 1.53.0 (which is what GitHub Actions is using) and `cargo build` worked fine.

There are a few solutions we could take:

- Specify minimum version of Rust in the README or elsewhere.
- Have a troubleshooting doc that recommends upgrading Rust if compilation fails. (I hear SmartNoise has a nice troubleshooting doc.)

**Comment by Shoeboxam** [comment]
This PR loosened the compilation requirements in 1.52: https://github.com/rust-lang/rust/pull/80732
It just shows that backwards incompatible code is not always obvious from the release notes, and that if we specify a minimum rust version, we need to pin CI to it and probably also develop with it.
