### ISSUE TITLE
Polars: reuse margin descriptors when possible

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1707]
Imagine you specify a margin descriptor like so:

```python
    margins={(): dp.Margin(max_partition_len=10_000)}
```

Then the max partition length should be known in the following query:

```python
(
    context.query()
    .group_by("A")
    .agg(pl.col("B").fill_null(0).dp.sum((0, 10)))
    .release().collect()
)
```

**Comment by mccalluc** [comment]
Sorry not to find this: Will the kwarg be `max_possible_rows`, or is that something different?

**Comment by Shoeboxam** [comment]
No worries! The kwarg is `max_partition_len`. It works out to:

`(): Margin(max_partition_len=max_possible_rows)`
