### ISSUE TITLE
Polars: filter

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1747]
**Description**
- **Note**: not the same as LazyFrame Filter
- **Constructor**: Transformation
- **Class**: Expr

--- 
reference: [Polars APIs sheet](https://docs.google.com/spreadsheets/d/1w4H-qrSe9pkvNT2NhowfiIHNWXSseOyMX2nu5H6-RkQ/edit?gid=0#gid=0)

**Comment by Shoeboxam** [comment]
Closed in #1534
