### ISSUE TITLE
make_base_discrete_laplace doesnt exist anymore in R package

### ISSUE THREAD

**Issue by LilianeTrafelet** [opendp/opendp#1764]
**Description**
I have been working with the opendp package (R)  for some month now. After I re-installed the package today the make_base_discrete_laplace does not exist anymore? Unfortunatly I cant look up what version of the opendp packge i Previously used.
 ( I am working with integers )

**To Reproduce**
library(opendp)  # v 0.10.0
enable_features('contrib')
dp_release_mechanism <- make_base_discrete_laplace(input_domain = vector_domain(atom_domain(.T = "i32")),
                                                           input_metric =l1_distance(.T = "i32"),
                                                           scale =  scale)

**Comment by Shoeboxam** [comment]
Hi Liliane! The API has been shortened: 

```R
enable_features('contrib')
dp_release_mechanism <- make_laplace(
	input_domain = vector_domain(atom_domain(.T = "i32")),
	input_metric = l1_distance(.T = "i32"),
	scale = scale)
```

The motivation for this is that it is sufficient to distinguish between discrete and continuous versions of the mechanism solely by the domain, so the extra info in the constructor is redundant.

**Comment by LilianeTrafelet** [comment]
Hi
Thank you for your quick response!
Unfortunately I still run in to an error when trying to execute your code snipplet 

```
> dp_release_mechanism <- make_laplace(input_domain = vector_domain(atom_domain(.T = "i32")),
+                                                            input_metric =l1_distance(.T = "i32"),
+                                                            scale =  scale)
Error in rt_assert_is_similar(expected = .T.scale, inferred = rt_infer(scale)) : 
  inferred type is Vec<f64>, expected f64. See https://github.com/opendp/opendp/discussions/298
```

the suggested github issue link did not help me, th elinked API documentation in this issue does not exist anymore (404)

**Comment by Shoeboxam** [comment]
Is your `scale` a vector? The code for me works when scale is scalar. This mechanism will only apply isotropic noise.

**Comment by LilianeTrafelet** [comment]
Thanks, yes it was indeed a vector, with a scalar it now works fine!

**Comment by Shoeboxam** [comment]
Great! Don't hesitate to post any other problems you might run into!
