### ISSUE TITLE
Community Survey

### ISSUE THREAD

**Issue by GKD-stack** [opendp/opendp#1787]
a starter notebook for the community data survey analysis that completes all the questions for below. just histograms for now, can incorporate other  visualizations later

What best describes you?
Primary Motivation
Level of DP
Primary Focus
Secondary Focus
Gender
Ethnicity
Region

**Comment by mccalluc** [comment]
Hand-off to Vikrant has been made. A PR was started (#1788), but I don't think the plan was to make this example part of the docs, so I'm closing.
