### ISSUE TITLE
sklearn.PCA not in API reference docs?

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1798]
Users would expect to find a section for `sklearn` in the API docs, but won't find it. I think it's because it's under the private `_extrinsics`.

Maybe we rearrange the packages? There are configuration options for autodoc, but I think that path would involve revealing `_extrinsics` in the docs, which I don't think we want.

**Comment by Shoeboxam** [comment]
This will be resolved by #1452.

**Comment by mccalluc** [comment]
There's a deeper problem we have with figuring out how to get code that needs optional dependencies to generate documentation correctly, but there's not a page in the api ref that can get people started: https://docs.opendp.org/en/stable/api/python/opendp.extras.sklearn.decomposition.html

Original scope of this issue is satisfied.
