### ISSUE TITLE
Create v0.11 Release Announcement

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#1819]
Folder with release drafts: https://drive.google.com/drive/folders/1rOR1-xPxjXfzQKE4yLlVUCa0DlCZjYNP

**Comment by mccalluc** [comment]
[done!](https://docs.google.com/document/d/1IUFZYnx0US4f_3KgB-YoZ4-2lBeJs_CcMwL0ujJ3jGE/edit#heading=h.pfs7cvovp4h2)
