### ISSUE TITLE
Extend coverage to include raise and except

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1830]
_Originally posted by @mccalluc in https://github.com/opendp/opendp/pull/1823#pullrequestreview-2191712841_

This PR also highlights that we've configured some exceptions in `.coveragerc`:
```
exclude_also =
  # TODO: Improve coverage and shorten this list!
  ^\s*raise\b
  ^\s*except\b
  os\.environ
  ^\s*\.\.\.\s*$
```

**Comment by mccalluc** [comment]
We'll first remove these from the ignore list, and add line-by-line ignores where needed, and then more slowly clean those up.
