### ISSUE TITLE
Compatible pairings of domains and metrics

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#185]
There is interest in using the type system to enforce compatible pairings of metrics and domains.

**Comment by Shoeboxam** [comment]
See https://github.com/opendp/opendp/tree/185-compatibility

**Comment by andrewvyrros** [comment]
Some discussion here: https://docs.google.com/document/d/1gmc35I2Ytgydc4Q5JxwoeF7may-WJUfdgmK1HGu1IWM/edit?usp=sharing
