### ISSUE TITLE
Make the polars docs public

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1862]
We've added JSON metadata to mark all of the polars notebooks as `orphan` pages. We'll want one big follow-up PR which:
- Removes the `orphan` tags.
- Adds the notebooks to the toctrees. (The notebooks should at least be in the right directory already. For the exact order see [Gurman's work plan](https://docs.google.com/document/d/1-adB1pgXtu9NBUKV6dlaMxx_73UeOurX8SzNMwOc_ls/edit#bookmark=id.zfqohqni4ig9).)
- Resolves any issues that arise when we read the docs from the top. (See #1863)
- In the quickstart, explain how Polars relates to the the Framework and Context API. (I think we don't want to describe our Polars interface as a third API? See #1800.)

**Comment by Shoeboxam** [comment]
Closed in #1953
