### ISSUE TITLE
Exception in Windows opendp installation

### ISSUE THREAD

**Issue by K-Meech** [opendp/opendp#1885]
**Describe the bug**
Opendp throws an error when imported in a fresh Windows installation (see below)

**To Reproduce**
I installed opendp as follows on a Windows 11 computer:
```
conda create -n opendp python=3.10
pip install opendp
```
When I `import opendp` it throws:

```
  File "C:\Users\kimme\anaconda3\envs\opendp\lib\site-packages\opendp\_lib.py", line 31, in _load_library
    raise Exception(f"Expected exactly one binary to be present. Got: {lib_dir_file_names}")
Exception: Expected exactly one binary to be present. Got: []
```

**Comment by Shoeboxam** [comment]
This will be fixed in 0.11, which we are now in the process of releasing. 

Until then, `pip install opendp==0.10.0a20240804001` should work properly.

Thanks for reporting this!

**Comment by K-Meech** [comment]
Thanks @Shoeboxam ! Using version `0.10.0a20240804001` works great.

**Comment by mccalluc** [comment]
👍 closing.
