### ISSUE TITLE
Flag older docs page as out of date

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#1978]
No idea how they got there, but one of the hackathon participants was looking at an older version of the docs. It took me a little while to realize why things were weird.

We could have a warning on all the docs pages for all the versions before the current one.

**Comment by SalilVadhan** [comment]
I got to an old version of the docs (0.2) by a Google search for "OpenDP
documentation".

**Comment by Shoeboxam** [comment]
Duplicate of #946
