### ISSUE TITLE
Releases probably shouldn't be sorted alphabetically

### ISSUE THREAD

**Issue by TedTed** [opendp/opendp#1995]
In the [documentation](https://docs.opendp.org/en/v0.11.0/index.html), if you open the "Releases" menu thing on the left bar, you see a list of releases which is ordered alphabetically, so the latest releases 0.10 and 0.11 end up between 0.1 and 0.2. You probably don't want that =)

**Comment by Shoeboxam** [comment]
Agree! Chuck fixed this in 4c7182d642a177fcd9c78453b3e7cc9aac38568e yesterday. Will go out once we fix our nightly build. Thanks for opening this. Will close once that goes out.

**Comment by mccalluc** [comment]
Update: The nightly build has been failing because of
- #1996

Keeping this issue open until we see the nightly build work.

**Comment by Shoeboxam** [comment]
Cleaning up old issues, ordering is now lexicographic on semver.
