### ISSUE TITLE
Confirm that we explain `honest-but-curious` where required

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#2020]
With this PR
- #2014 

the required features are generated and included in the documentation. We would also like explain _why_ the `honest-but-curious` flag is required... and if an explanation is missing, that should be a CI failure.

(Explanations don't seem so important for the other flags: With `contrib` either the proof is vetted or not -- I don't think we want to try to explain why something is almost safe.)

Before #2014 we had precisely one of these explanations: It was removed, but it should be added back:
```
        add_section_to_description("Features");
```
```
/// # Features
/// * `honest-but-curious` - The privacy guarantee governs only at most one evaluation of the released expression.
```

For background:
- #1662 had a vague scope: some work was done, but this new issue is more clear about what still needs to be done.
- #1968 went part-way toward a solution... but it is old, so it might make more sense to start a new branch and reuse pieces of it.

**Comment by mccalluc** [comment]
@Shoeboxam : Thoughts about how this should be implemented? A few ideas:
- If it has the `honest-but-curious` feature, we look for for "honest-but-curious" in the docstring during codegen, and panic if it's not there.
- Slightly more structured: If it has `honest-but-curious`, we look for a "# Why honest-but-curious?" header.
- Or move this into in the metadata. Something like:
```
#[bootstrap(
    features("honest-but-curious"),
    why_flagged("Privacy guarantees only apply if:
1. The LazyFrame (compute plan) is only ever executed once.
2. The analyst does not observe ordering of rows in the output. To ensure this, shuffle the output."),
```
Insert the explanation after the generated list of features, and error if not present.

**Comment by Shoeboxam** [comment]
Comments on each bullet, respectively.

* I kind of liked the approach in https://github.com/opendp/opendp/pull/1664. It automatically pushes contributions into the right behavior.
* A perk of making it into a header is that you can then control ordering of that section in the generated output. 
* Could be inconvenient to write with formatting, especially if it gets longer, and makes rust second-class.

I like 2 most. Now that features are passed into docstring.rs, you could just check for that section in the parsed docstring.

**Comment by mccalluc** [comment]
Option two it is. Thanks!
