### ISSUE TITLE
Check trailing underscores on `and_`, `or_`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#2039]
Underscores are not in the [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1w4H-qrSe9pkvNT2NhowfiIHNWXSseOyMX2nu5H6-RkQ/edit?pli=1&gid=0#gid=0), but are in [polars docs](https://docs.pola.rs/api/python/stable/reference/expressions/operators.html#conjunction)

Confirm that our behavior matches Polars, and document.

**Comment by Shoeboxam** [comment]
Our behavior matches polars, I've updated the spreadsheet.
