### ISSUE TITLE
Read the max_possible_rows from the () margin

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#2102]
> OpenDP should read the max_possible_rows from the () margin and not need any of the other margins when grouping by any keys. This is now causing pain down here in DPCreator.

_Originally posted by @Shoeboxam in https://github.com/opendp/dp-creator-ii/pull/48#discussion_r1793566621_

**Comment by Shoeboxam** [comment]
To be resolved by #2091, dupe of #1707. Hope you don't mind if I close this! :P
