### ISSUE TITLE
add quotes to `pip install 'opendp[polars]'`

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#2136]
With just
```
pip install opendp[polars]
```
the shell tries to parse the square brackets, and fails:
```
zsh: no matches found: opendp[polars]
```
We should make sure it any extra installs are quoted in the docs:
```
pip install 'opendp[polars]'
Requirement already satisfied: opendp[polars] in ./.venv/lib/python3.12/site-packages (0.11.1)
```

**Comment by devfernandoa** [comment]
Hi there, I'd love to help on this issue!

**Comment by mccalluc** [comment]
@devfernandoa -- Sure: probably just search for `opendp[` across the docs and submit a PR.
