### ISSUE TITLE
Basic Integration Tests

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#236]
Starting point for library integration tests. First pass would be stuff needed for integration with DP Creator.

- List of DPCreator statistics to include with integration tests, starting with univariate stats
   - https://docs.google.com/spreadsheets/d/1L-LWTf7PMZBbCuQxSbAFQkZKEtb6AgsK3qF6lwY_xrA/edit#gid=0

**Comment by raprasad** [comment]
- List of DPCreator statistics: https://docs.google.com/spreadsheets/d/1L-LWTf7PMZBbCuQxSbAFQkZKEtb6AgsK3qF6lwY_xrA/edit#gid=0
