### ISSUE TITLE
Utilities to simplify app development (especially for DP Creator)

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#237]
When writing OpenDP apps, it's a little awkward to specify the noise scale of a Measurement. A more typical mindset for an app developer is to provide a desired privacy loss. We need some utilities to bridge this gap.

The canonical use case is constructing the set of Measurements offered in DP Creator.

A simple solution would be single-use functions that map from privacy loss -> sigma for a given mechanism, but this is a bit limiting. More flexible would be a binary search approach.

Since these things would be generally useful to the library, the best solution would be to add a Rust module with Python bindings. If that turns out to be too complicated, a first cut could be simple Python-only helper functions.

**Comment by Shoeboxam** [comment]
We want to accept a predicate to this binary search function, and we don't have the means to share functions across languages at this time. So I vote for separate implementations.
