### ISSUE TITLE
Port of remaining SmartNoise notebooks

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#238]
After we have a reasonable version of #199, we should look at converting the remaining SmartNoise notebooks to use OpenDP directly.

Ready:
- [x] https://github.com/opendp/opendp/issues/332
- [x] https://github.com/opendp/opendp/issues/333
- [ ] https://github.com/opendp/opendp/issues/334
- [x] https://github.com/opendp/opendp/issues/335

Missing dependencies:
- [x] https://github.com/opendp/opendp/issues/336
- https://github.com/opendp/smartnoise-samples/blob/master/analysis/covariance.ipynb
    - needs data munging transformations, covariance is multivariate
- https://github.com/opendp/smartnoise-samples/blob/master/analysis/tutorial_mental_health_in_tech_survey.ipynb
    - needs filtering

**Comment by Shoeboxam** [comment]
Many of the notebooks use features that are not available in OpenDP, like filtering. I've opened individual issues for these ports.

**Comment by raprasad** [comment]
Closing, leaving remaining issue, #334, open
