### ISSUE TITLE
Add a workflow to automatically check code style on PRs

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#256]
We should add a workflow that checks code style via rustfmt, pep8, etc, and leaves comments on PRs when submitted. (This is less onerous than using pre-commit hooks, and the feedback feels friendlier when it comes from a robot than a human reviewer.

Suggested implementation: https://github.com/reviewdog/reviewdog#github-action-reviewdogaction-setup

**Comment by mccalluc** [comment]
This could be useful, but it's probably several parallel efforts:

## python

Flake8 (a superset of pep8) has been in place for a while: https://github.com/opendp/opendp/pull/62/files ... but we're only requiring a subset of its rules to pass: any other violations are just warnings:

```
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```
("`--select errors`: Limit the reported error codes to codes prefix-matched by this list.")

It would be low-cost to see how many other rules we are already in compliance with, and require those to pass going forward.

### ... inside notebooks?

Options include https://github.com/nbQA-dev/nbQA and https://github.com/s-weigand/flake8-nb.

## rust

rustfmt is mentioned in the instructions, but it is not used in CI, as far as I can tell.

clippy is complementary to rustfmt: Also mentioned in instructions, but not used in CI as far as I can tell.

## r

[lintr](https://lintr.r-lib.org/) seems to be the default. I don't think there is yet any R code in `main`, but this might be something to have in place when it is merged to `main`.

## reviewdog

It looks nice: I think the first step would be to just to get the cli tools running in ci, and once something is there, we could use this for a prettier UI.

**Comment by raprasad** [comment]
- closing and opened #1342
