### ISSUE TITLE
Docs Update -- Quickstart

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#268]
Fill in the content of docs/source/quickstart.

I think we can largely copy the content from user/getting-started (then add more detail to the latter).

**Comment by pdurbin** [comment]
I'm getting the following error when I try the steps from the from the Getting Started page.

```
Successfully installed opendp-0.2.0
(venv) HMDC-beamish:asdafsfsad pdurbin$ python
Python 3.9.6 (default, Jun 29 2021, 06:20:32) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from opendp.trans import make_identity
>>> from opendp.typing import SubstituteDistance
>>> 
>>> identity = make_identity(M=SubstituteDistance, T=str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: make_identity() got an unexpected keyword argument 'T'
>>> 
```

Here's what I'm following (the current commit is ba776a2).

![Screen Shot 2021-09-09 at 2 19 30 PM](https://user-images.githubusercontent.com/21006/132741369-59f913d6-90b8-40e4-aedf-bf0eff50e693.png)

**Comment by pdurbin** [comment]
> unexpected keyword argument 'T'

It looks like this is supposed to be `TA=str`. I'll fix it in the Getting Started page and use the right form in the Quickstart.
