### ISSUE TITLE
Merge build instructions from Quick Start into Developer Guide, replace with a link

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#288]
We have similar instructions in the developer guide. I'm not sure if it is different enough for the doc duplication to be necessary, or if it makes sense to somehow merge and replace one of these with a link.

```rst
.. _my-link:
```

Up to you.

_Originally posted by @Shoeboxam in https://github.com/opendp/opendp/pull/287#discussion_r709022786_

**Comment by Shoeboxam** [comment]
These instructions seem different enough that I think they could/should remain separate.
