### ISSUE TITLE
Docs Section: Why do you need differential privacy?

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#317]
We should add a docs page that makes the case for why you need differential privacy in general, based John Abowd's suggestion in his talk. 
- overview of attacks
- use cases
- port attack notebooks from smartnoise-samples (could be a good base, but any attack is valid) 
    - https://github.com/opendp/opendp/issues/335
- link to notebooks from these docs
- communicate how we perform a worst-case analysis

**Comment by raprasad** [comment]
Closing for #998
