### ISSUE TITLE
CSV Loader -- Implementation

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#326]
It would be nice to have a transformation from a csv path to a DataframeDomain of String columns.

Some considerations:
- need to add a strange CsvPathDomain, and define dataset distances between dataset paths
- could just emit the string contents of the file, and be chained with `make_parse_dataframe`
- on the other hand, parsing types up-front reduces memory requirements

**Comment by raprasad** [comment]
Closing. Will be resolved with Polars
