### ISSUE TITLE
Quote escaping in `make_split_dataframe`

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#328]
Many CSV files are written out with quoted columns. When `make_split_dataframe` runs, it doesn't remove these quotes. This can lead to surprise quotes in your columns and failed casting. 

Misc approaches for quote escaping:
- add a transformation that strips quotes
- add more options for different csv formats to `make_split_dataframe` and related constructors
- determine if the [csv crate](https://crates.io/crates/csv) can be taken on as a dependency ([prior implementation](https://github.com/opendp/smartnoise-core/blob/develop/runtime-rust/src/components/materialize.rs))

We may also want to consider rewriting `make_split_dataframe` to just be a chain of `make_split_rows` and `make_split_records`. Are there performance downsides to replacing the current implementation with a straightforward chaining?

**Comment by raprasad** [comment]
Closing. Will rely on Polars in future versions
