### ISSUE TITLE
Simple Attack Notebook Port

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#335]
We have a notebook demonstrating a simple privacy attack here, but it's in the old library:
https://github.com/opendp/smartnoise-samples/blob/master/attacks/simple_attack.ipynb

It just has a differencing attack; it would be good to look into other attacks as well.

**Comment by orespo** [comment]
Hi Mike, I've been working on it and actually almost done. I have just one question in order to solve it, so let me put it here:
I used the transformation `make_bounded_resize`, in similar manner to `sn.resize` function used in the old notebook.  Then I need to compute the mean that is known to the attacker, on the smaller set. However, I'm not sure how does `make_bounded_resize` truncates the data and I haven't found about it either in the documentation: do you always truncates the last records?

**Comment by Shoeboxam** [comment]
@orespo Sorry about the long message. I've been thinking about the resize a lot recently, because we've been trying to stabilize one of the sized aggregator proofs. We need more formalization for the resize transformation as well as formalization for how we treat data ordering. 

The current implementation is here:
https://github.com/opendp/opendp/blob/main/rust/opendp/src/trans/resize/mod.rs

If n < data.len(), then the first n records are kept. 
If n == data.len(), then the data is passed through. 
If n > data.len(), then `n - data.len()` constants are added.

In the previous library when `n < data.len()`, we sampled n records randomly without replacement. I didn't implement the same random subsetting in OpenDP because the metric is SymmetricDistance, which is a metric on unordered sets! I think this is not right.

The choice of using vectors is purely for implementation reasons (cache-locality, and looser trait bounds), but does not reflect the theory. A more accurate domain/metric pairing would be to use something more like a HashSet instead of a Vec, because a Vec imparts a natural ordering on the data. By taking the first n values, I'm taking advantage of ordering when I shouldn't be. 

It's kind of a very general problem anytime we use a method on a vector that depends on the data ordering. There's a similar unresolved issue with saturating arithmetic in the unknown n sum aggregator. Using saturating arithmetic makes the sum function robust to overflow, but at the same time sensitive to data ordering. Salil proposed that maybe we could just switch to modular arithmetic and introduce a ModularDistance metric to be used instead of AbsoluteDistance. In this approach the noise mechanisms wrap around. Maybe we should also explore an alternative to SymmetricDistance for ordered data.

**Comment by Shoeboxam** [comment]
I think the more immediate issue is with the resize relation. I wrote it with an equivalent number of additions and removals in mind. But in the worst case, either d_in removals or d_in additions are made. So the correct relation is not `d_out >= d_in + d_in % 2` (rounding up to the nearest even, assuming a nearly even edit distribution); the correct relation is `d_out >= d_in * 2`.

**Comment by orespo** [comment]
Ok, the implementation is now clear to me, and I suggest also to document it.

But more importantly, let's talk about the ordering: if you always load data from csv then there is a natural ordering, but of course its really not clear to me whether it should be considered at all. Should we assume it always unordered data? then the resize is not well defined without any compare function between any two records in it (is it reasonable to require it? you can always set some default method)
