### ISSUE TITLE
R language bindings

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#365]
Support for the R language is a very common request!

There is a stub R library I wrote in this private repo here:
https://github.com/opendp/smartnoise-core-R

**Comment by raprasad** [comment]
replaced by #663 (This issue was attached to a closed PR)

**Comment by Shoeboxam** [comment]
@raprasad It's ok (and ideal) to attach multiple failed PRs to one issue. Sometimes it takes more than one attempt to close an issue.

**Comment by Shoeboxam** [comment]
Closing this rollup issue in favor of the milestone:
https://github.com/opendp/opendp/milestone/14
