### ISSUE TITLE
Rationalize types for LaplaceMechanism and GaussianMechanism

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#37]
LaplaceMechanism and GaussianMechanism currently support any primitive types (including integers), which is probably not what we want. We need to rationalize this. Simplest solution would be to support f64 only, but we should think this through.

**Comment by Shoeboxam** [comment]
Fixed in #24. Laplace and gaussian mechanisms are generic over floating point types. The geometric mechanism is generic over integer types.
