### ISSUE TITLE
Mental Health Notebook Port

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#380]
- depends on #366 

---

Port the mental health notebook to the opendp library:

https://github.com/opendp/smartnoise-samples/blob/master/analysis/tutorial_mental_health_in_tech_survey.ipynb

(Note: this notebook was originally created by @MayanaPereira)

**Comment by Shoeboxam** [comment]
Now that we have filtering (the lib calls it subsetting), this notebook should now be ready to port.

**Comment by mccalluc** [comment]
Closing. The tutorials are being built around a different data set.
