### ISSUE TITLE
Snapping Mechanism Notebook (port from SmartNoise)

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#389]
In Aug. 2020, @ctcovington created a notebook for SmartNoise on the Snapping Mechanism. 

This may be used as a starting point for an OpenDP notebook.

- Original file in SmartNoise: https://github.com/opendp/smartnoise-samples/blob/67a208bf1e3e6e8f1669860dbb4450ba54b8728b/analysis/snapping_mechanism.ipynb

**Comment by ctcovington** [comment]
Just wanted to clarify that the notebook above isn't really about the snapping mechanism, but rather about what the notion of algorithm "accuracy" actually entails in the system and how it can be potentially misleading. 

There is a snapping notebook here though. https://github.com/opendp/smartnoise-samples/blob/67a208bf1e3e6e8f1669860dbb4450ba54b8728b/analysis/snapping_mechanism.ipynb

**Comment by raprasad** [comment]
Thanks @ctcovington, grabbed the wrong link. (The accuracy pitfalls notebook port is underway: https://github.com/opendp/opendp/issues/332)

**Comment by Shoeboxam** [comment]
Closed via #506. We now have an efficient and exact laplace sampler, so the snapping mechanism isn't necessary.
