### ISSUE TITLE
Clean up outstanding style/format issues

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#417]
We've been pretty good about code style, but still have some places where formatting is funky. These tend to get fixed up on an ad-hoc basis when formatting a file in the IDE. This is a hassle for PR reviews, as it introduces spurious diffs.

We should make a separate change, where we clean up all rustfmt/clippy/pep8/whatever issues, and get to a clean slate.

Then moving forward, we should enable style checks for PRs (#256).

**Comment by Shoeboxam** [comment]
Closed in #668.
