### ISSUE TITLE
Python API docs for old releases are same as latest

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#432]
See example:
https://docs.opendp.org/en/v0.1.0/api/python/opendp.meas.html

In the above example, the documentation includes things like `make_base_ptr`, which don't exist in v0.1.0.

**Comment by andrewvyrros** [comment]
Dang it! Looks like the `smv_prebuild_command` setting for `sphinx-multiversion` plugin runs only once at the beginning of docs generation, rather than once per version.

**Comment by Shoeboxam** [comment]
It was actually because the path variable was not pointing to the temp directory with the versioned sources.
