### ISSUE TITLE
Comments error

### ISSUE THREAD

**Issue by zhaozirun** [opendp/opendp#438]
**Describe the bug**
opendp/python/src/opendp/mod.py
Row 385 should be '<'

**To Reproduce**
Code snippet to reproduce the behavior.

**Comment by Shoeboxam** [comment]
Actually, it's line 386 that should be flipped, but yes, there is an issue there. Thanks for pointing it out!

On 385, I want to find a x > 5, such that the result is no greater than 5 by at most 1e-8. 
On 386, I want to find a x < 5, such that the result is no less than 5 by at most -1e-8. 

Updated in the linked PR.
