### ISSUE TITLE
Geometric variates via binary search

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#457]
We should explore sampling geometric random variates via binary search so that the sampling runs in logarithmic time instead of linear time. 

The linear time algorithm we currently have runs very slow when the scale parameter is large.  We repeatedly flip a biased coin until finding a heads. The number of failed flips is our geometric sample. 

However, we can repeatedly split the support at the expectation, by making unbiased coin flips to determine if the sample is in the lower or upper portion of the support. Continue to sample standard bernoullis until a falsey, which narrows the support to a band. I'm not sure how to sample from this band, though. One approach is to reuse our current implementation, but use rejection sampling. This reintroduces time complexity issues. 
Another approach is to continue working out midpoints of the band. The geometric distribution is nice in that it is memoryless, so cutting it at any point still produces a geometric distribution, but we are working with a censored geometric distribution. It may be that computing the midpoint of the censored geometric introduces floating-point vulnerabilities.

**Comment by peteroupc** [comment]
For the geometric distribution with small values of _p_ (I assume _p_ is 1 divided by the scale parameter), there is an exact and efficient algorithm published in Bringmann, K. and Friedrich, T., 2013, July. Exact and efficient generation of geometric random variates and random graphs, in International Colloquium on Automata, Languages, and Programming (pp. 267-278). However, the algorithm is not exactly trivial and its description there is not necessarily programmer-friendly.

See my [notes on a geometric sampler](https://peteroupc.github.io/randmisc.html).

On the other hand, when p is at 1/3 or greater, the trivial algorithm of drawing Bernoulli(_p_) trials until a success happens "is probably difficult to beat in any programming environment" (Devroye, L., "Non-Uniform Random Variate Generation", 1986, p. 498).

See also rust-random/rand#1062.

**Comment by Shoeboxam** [comment]
@peteroupc Wow, I wasn't expecting to find you here! I'm really happy to get this message. I actually stumbled on this algorithm and your implementation, and have been trying to get it to work in rust in this geometric sampler context. I just pushed a branch with my initial attempt at this from April here:
https://github.com/opendp/opendp/commit/6f816b37a34c98b390c4ca898f8336bb935cba8d

I haven't quite solved it yet, mainly because I think I need a better approach to fractionalize the float with smaller constants. My constants are so large that the algorithm is very susceptible to overflow. So I think either a better fractionalization or just larger data types will be necessary.

I was anticipating using the existing linear-time sampler when the success probability was high, as you mention, but wasn't sure where to set the cutoff. I figured I might do it with some empirical testing, but the 1/3 bound is useful. 
[I'm very informally using 16 trials as a cutoff at the moment.](https://github.com/opendp/opendp/commit/6f816b37a34c98b390c4ca898f8336bb935cba8d#diff-d1fa6f1faf7382d159fbb894abe4884a3ba4f13745f4bc956a9be9851fc25844R64-R71)

**Comment by Shoeboxam** [comment]
@peteroupc As a follow-up to this, I ended up using this paper: https://arxiv.org/pdf/2004.00010.pdf. You might find the samplers in Section 5 interesting, as they accomplish geometric sampling more efficiently [than is done here](https://peteroupc.github.io/morealg.html#Symmetric_Geometric_Distribution) and more simply [than is done here](https://peteroupc.github.io/randmisc.html#On_a_Geometric_Sampler).

Do you have any general guidance or thoughts on how one might partially sample from the Gumbel distribution, parameterized by both shift and scale? I have an algorithm that would benefit from this-- the gist is to independently add Gumbel noise to a vector, and release the indexes of the top k.

**Comment by peteroupc** [comment]
A "Gumbel" random variable has density $\exp(x) \exp(-\exp(-x))$.

It can be generated by rejection from the exponential distribution, as follows:

1. Generate an exponential random variate, which can be done using the von Neumann algorithm described in either Karney (2016) or improved versions that cite it.
2. Accept the variate with probability $\exp(-\exp(-x))$ (there's a Bernoulli factory algorithm for this, with $x$ separated into its fractional and integer parts), or go to step 1 otherwise.

**Comment by Shoeboxam** [comment]
Thanks for the response! This is a promising approach, but I had trouble sampling $Bernoulli(p = \exp(-\exp(-x)))$ with [the algorithm you linked](https://peteroupc.github.io/bernoulli.html#exp_minus__m____lambda_____mu). Specifically breaking $\exp(-x)$ into $m$, $\lambda$ and $\mu$ in such a way that $m$ is integral, and there exists factories for $\lambda$ and $\mu$ (as I understand it, $\lambda$ and $\mu$ need not necessarily be fractional). I still don't see anything that excludes trivially letting $m = 0$, $\lambda = exp(-x)$, $\mu = 1$, but clearly that doesn't lead to a sensible algorithm (it always returns 1!).

I was able to sample $Bernoulli(p = \exp(-\exp(-x)))$ by combining the Cannone et al. sampler for $\exp(x)$, as well as [your rendition of the sampler](https://github.com/peteroupc/peteroupc.github.io/blob/master/bernoulli.py#L995-L1018) from Łatuszyński et al. Unfortunately, this implementation of the Łatuszyński sampler becomes biased when $x \ge 1$ (when success probability > .5).

**Comment by Shoeboxam** [comment]
@peteroupc Would you rather I move/continue this discussion in the feedback issue of your repo?

**Comment by peteroupc** [comment]
Yes you may.
