### ISSUE TITLE
Python library project structure

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#53]
Organize the Python code into a rational structure for a library.

Currently, the Python wrapper code is just sitting in a bare scripts. This should be reorganized into a proper library project. Proposed layout:

```
opendp/
    python/
        docs/
        opendp/
            __init__.py
            opendp.py
            ...
        requirements.txt
        tests/
            ....
```

**Comment by Shoeboxam** [comment]
Do you have experience making python packages? I could set up the bones.
