### ISSUE TITLE
Mark Repositories as belonging to the "Commons"

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#547]
To discuss

- Are repositories within the opendp org, other than the library, considered as part of the commons? 
- How can we "mark/label" these repositories--perhaps a badge?
- Where should a description of the commons live? In this repository?

**Comment by Shoeboxam** [comment]
Q: Where should a descriptions of the commons live?
A: https://docs.opendp.org/en/stable/opendp-commons/index.html

**Comment by mccalluc** [comment]
## Org vs commons?
> Are repositories within the opendp org, other than the library, considered as part of the commons?

It surprised me, but no: [Salil writes](https://github.com/opendp/opendp/issues/979#issuecomment-1789873928):
> However, the OpenDP Commons should
> include the OpenDP Library, but not SmartNoise.  It is more about community
> ownership and governance rather than the nature of the software itself.

## How to identify?
> How can we "mark/label" these repositories--perhaps a badge?

Using a github "topic" would be good: We could link to a complete list. [My previous lab](https://github.com/topics/gehlenborglab), for example.

## Where to describe?
> Where should a description of the commons live? In this repository?

I'd prefer to leave the description of the opendp commons to the project site. Better to do it in just one place, and do it clearly. The [current description of commons](https://opendp.org/tools#block-boxes-1646402175) on the project site could
- have a diagram which accurately indicates what is in the commons. (SmartNoise is not.)
- Use the github topic to link to a full list.
- Include an operational definition: If this is meaningful, we should be able to say what it is.

**Comment by mccalluc** [comment]
- opendp
- dp-creator
- dp-logger

**Comment by mccalluc** [comment]
[The three repos are tagged.](https://github.com/topics/opendp-commons)

People can use that link, but as discussed, github repo topics are not something we can control: Anyone can add `opendp-commons` to their repo. If this is a concern, then you'll need to make use of the organization. One possible way to explain the relationship between projects would be create an organization README, but I think the status quo is fine.

from the github docs:
> Create a public repository called .github. Once created, add a /profile/README.md. The README will appear on your organization's profile, visible to anyone. 

Closing!
