### ISSUE TITLE
`histograms.ipynb` fails on Binder

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#606]
Example notebook `histograms.ipynb` (and presumably others) doesn't work on Binder because it needs `matplotlib`. I believe there's a config file we can drop somewhere for dependencies.

**Comment by Shoeboxam** [comment]
Config file located here: https://github.com/opendp/opendp/tree/main/.binder

**Comment by Shoeboxam** [comment]
I wonder if it could just contain `-r ../docs/requirements_notebooks.txt`?

**Comment by mccalluc** [comment]
- Issue #903 was essentially a duplicate of this
- PR #910 fixed it [by adding `-r ../docs/requirements_notebooks.txt`](https://github.com/opendp/opendp/pull/910/files#diff-7027aa145ff352398f38b1cdccf34168731f4bd060315d3e3c4512bc9268dcb2), as you suggested above.

This can probably be closed?

**Comment by Shoeboxam** [comment]
Thanks for noticing the dupe @mccalluc!
