### ISSUE TITLE
`discrete_gaussian_scale_to_accuracy` edge case

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#626]
`discrete_gaussian_scale_to_accuracy` returns an accuracy one too large when the scale is on the lower edge.

Reported by @alexWhitworth:

```python
import opendp.accuracy as dp_a
acc = 2.
dp_a.discrete_gaussian_scale_to_accuracy(
    dp_a.accuracy_to_discrete_gaussian_scale(accuracy= acc, alpha=0.1)
    , alpha= 0.1
) 
# returns 3.0, not 2.0
```

Thanks for the report!

Solution:
The continuation condition in the loop should be `total > 0.`, not `total.is_sign_positive()`. That is, the loop should break if the total is negative **or exactly zero**.

**Comment by alexWhitworth** [comment]
And with Laplace:

```
dp_a.laplacian_scale_to_accuracy(
    dp_a.accuracy_to_laplacian_scale(2., alpha=0.1)
    , 0.1
) 
# returns 1.9999999999999998  -- so, float precision error

# But not a problem with discrete
dp_a.discrete_laplacian_scale_to_accuracy(
    dp_a.accuracy_to_discrete_laplacian_scale(2.,0.1)
    , 0.1
)  # returns 2.0
```

**Comment by Shoeboxam** [comment]
To improve float precision on the continuous laplace (using `*/` to denote either `*` or `/` depending on direction):

Current:
```rust
accuracy */ alpha.recip().ln()
```

Optimized:
```rust
-accuracy */ alpha.ln()
```
