### ISSUE TITLE
Change `make_base_geometric` from "deprecated" to an "alias"

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#643]
I don't think we actually want to completely remove the "geometric mechanism", as it's likely what some people will look for first. It just needs to be a thin alias.

**Comment by mccalluc** [comment]
I looks like this `make_base_geometric` was entirely removed in august of 2023, so this is moot.
> replace `make_base_geometric` with `make_base_discrete_laplace`

Closing.
