### ISSUE TITLE
Update citation.cff to include individual contributors

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#680]
Update initial `authors` section to include all contributors.

(changed after @Shoeboxam's comment below)

**Comment by Shoeboxam** [comment]
We merged a CITATION.cff. You can use `Cite this repository` on the rightpanel of the repo root to retrieve a formatted citation.

**Comment by raprasad** [comment]
@Shoeboxam - updated issue to be more specific

**Comment by raprasad** [comment]
Should we use this or an acknowledgements page
