### ISSUE TITLE
Include whitepapers in this repository

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#72]
Similar to SmartNoise, [whitepapers](https://github.com/opendp/smartnoise-core/tree/develop/whitepapers/accuracies) should be included in this repository. Previously both PDF and .tex formats were saved.

- Include whitepapers in this repository
  - What is the format for these proofs? (Salil)
- What is the process for editing/pull requests?
  - Document process. (Recommendation to use Overleaf / Link to overleaf version?)
- ReadMe with guide to whitepapers. (e.g. "table of contents"/links)
- Should the code itself (implementations of components, etc.) include links to whitepapers?

---
cc/ @pdurbin

**Comment by Shoeboxam** [comment]
See also #56

**Comment by raprasad** [comment]
Old issue. Initial proof infrastructure is in place
