### ISSUE TITLE
Test docs as part of PR validation

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#725]
Docs are generated after PRs are merged, so it's possible to break the docs without realizing it.

We should have a step somewhere (probably `smoke-test.yml`) that tests docs, too.

**Comment by Shoeboxam** [comment]
Is this resolved by just calling `make html` in `smoke-test.yml`? Or did you have more in mind-- like pushing to a staging site that you can load?

**Comment by andrewvyrros** [comment]
I was initially thinking that we should rebuild all versions, because that's broken in the past, and we didn't notice until trying to make a release. But that takes a long time, and would make `smoke-test` even slower.

But with #880, we'll at least be building everything nightly, so I think that's enough.

**Comment by andrewvyrros** [comment]
With the docs build that happens in `nightly` now, I'm going to call this done. If we want to add something to `smoke-test`, we can open another issue.
