### ISSUE TITLE
Links from Python API docs to Rust API docs always use latest branch

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#728]
For example: https://docs.opendp.org/en/v0.6.2/api/python/opendp.measurements.html#opendp.measurements.make_base_discrete_gaussian points to https://docs.rs/opendp/latest/opendp/measurements/fn.make_base_discrete_gaussian.html.

`make_rustdoc_link` looks like it's doing the right thing, not sure what's breaking.

**Comment by andrewvyrros** [comment]
This looks like it'll be fixed by #716 & #718.

**Comment by raprasad** [comment]
Closing. (^ Issues above are complete)
