### ISSUE TITLE
Support aarch64-linux

### ISSUE THREAD

**Issue by madhavajay** [opendp/opendp#817]
**Describe the bug**
It appears that the wheel ships with precompiled binaries for x86_64 except for the Apple .dylib which is a universal fat binary.

Unfortunately this means `opendp` won't work on Arm64 (aarch64) linux nor will it run in a container on Apple Silicon since macOS will run aarch64 linux.

Are you able to provide aarch64 linux support? The same thing will eventually be an issue on Windows Arm64 too.

**To Reproduce**
pip install on linux on an arm64 cpu.

output from file tool:
```
file libopendp.so
libopendp.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a4467d4313afcd5f01ff0a4253ebc53810f68cef, with debug_info, not stripped

file libopendp.dylib
libopendp.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit x86_64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|NO_REEXPORTED_DYLIBS|HAS_TLV_DESCRIPTORS>] [arm64]

file opendp.dll
opendp.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows
root@backend-0:/usr/local/lib/python3.11/site-packages/opendp/lib#
```

**Comment by Shoeboxam** [comment]
Hi Madhava, thanks for opening an issue, I didn't realize we had this gap. We build our release binaries via manylinux docker containers on CI. Perhaps we could resolve this by distributing another binary built with the `manylinux2014_aarch64` platform tag. 

Do you have experience with this? I assume we'd end up with two `.so` files, and the library would choose amongst them? Thanks.

**Comment by madhavajay** [comment]
@Shoeboxam I think all the cool kids are using `cibuildwheel` these days. 

Not sure if you are using `pyo3` or not but there should be some good steps on combining it with rust.
https://github.com/pypa/cibuildwheel/issues/134
https://github.com/etesync/etebase-py/blob/master/.github/workflows/manual.yml

For now a `manylinux2014_aarch64` would definitely do the trick.

Let me know how I can help.

**Comment by andrewvyrros** [comment]
Thanks @madhavajay! We don't use `pyo3`, we're compiling a shared library ourselves.

The trouble is that we use the `gmp-mpfr-sys` crate, which builds `gmp` from source, which has hand-rolled assembly for all the different architectures. I had a heck of a time trying to get cross compilation to work with the standard `manylinux2014` docker images. The `gmp` configure script just doesn't want to go with the cross-compile toolchain.

But it looks like [rust-cross/manylinux-cross](https://github.com/rust-cross/manylinux-cross) will save us. It has a sane toolchain pre configured for cross compiling. I was able to get through the `gmp` build and generate an aarch64 binary from an x86_64 container, so I think we're looking good. (Still need to write the loading glue.)
