### ISSUE TITLE
SQL: Mark components needed for full SQL support

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#9]
Meet and mark Column C on the components list: 
https://docs.google.com/spreadsheets/d/132rAzbSDVCKqFZWeE-P8oOl9f23PzkvNwsrDV5LPkw4/edit#gid=0

**Comment by andrewvyrros** [comment]
We're not tracking SQL in the components spreadsheet anymore. If/when we look at SQL support in the future, we can work out a plan.
