### ISSUE TITLE
`OnceFrame` for single-evaluation lazyframe releases

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#901]
The experimental Polars APIs currently release a `LazyFrame`, which is an object that can be collected multiple times, each time with different random noise values. Introducing a newtype `OnceFrame` around `LazyFrame` could resolve this, by only allowing a single collection, but allowing pass-through of certain whitelisted methods- like collect or sink.

**Comment by mccalluc** [comment]
- #1602

OnceFrame is implemented: closing.
