### ISSUE TITLE
Ensure that notebooks can run in Binder out of the box

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#903]
(Follow-up from discussion https://github.com/opendp/opendp/discussions/898)

The first cell of `first-look-at-DP.ipynb` failed for me on Binder because pandas is not installed. Should fix it by adding pandas to `.binder/requirements.txt`.

(... but `smoke-test.yml` seems like it should be testing notebooks with `pytest --nbmake source/**/*.ipynb -n=auto`, so maybe that test isn't working as intended?)

I'll try starting a PR, and will update here with what I learn. 

Ideally, close when all notebooks work in Binder if cells are evaluated in order, and CI tests fail if this is not true.

**Comment by mccalluc** [comment]
New plan from https://github.com/opendp/opendp/pull/905#issuecomment-1667075429:

> After thinking about it a bit, I think the ideal approach is to:
> 
>  1.   Don't show a binder link for versions 0.7 or below (their .binder/requirements are broken)
>  1.   Don't show a binder link for nightly (the images take too long to build and constantly get rebuilt)
>     -    if you want a nightly build, you're better off setting things up locally
>  1.   Adjust .binder/requirements to -r install the existing ../docs/requirements_notebooks.txt
>     -    because .binder is not the source of truth for notebook dependencies
> 
> At this point, all Binder links will disappear from the docs site, but when we cut 0.8 (sometime within the next week), stable and 0.8 will have links.

In addition, might add a note to emphasize that the test is not about the current state of the code, but to ensure that the documentation of released versions is consistent

**Comment by Shoeboxam** [comment]
#910 affects this:

1. Not done. Do we still want to do this?
2. Fixed the binder link on nightly instead.
3. Done.
