### ISSUE TITLE
cannot import name 'make_bounded_resize' from 'opendp.transformations'

### ISSUE THREAD

**Issue by lo2aayy** [opendp/opendp#924]
Whenever I try to import any opendp library, I first get this error: 

`ImportError: cannot import name 'make_bounded_resize' from 'opendp.transformations' (/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/opendp/transformations.py)`

and then when I rerun it, it works normally. Any idea what might be the issue or how to mitigate it?

**Comment by Shoeboxam** [comment]
What version of OpenDP are you on? Might you have OpenDP 0.6 on one interpreter, and 0.7 or 0.8 on another?

**Comment by andrewvyrros** [comment]
This sounds like it was a version issue vs the documentation. If you're still seeing this problem, please feel free to reopen!
