### ISSUE TITLE
Add `seealso::` directive to `then_*` Sphinx documentation

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#935]
The `then_*` docs should contain a stub and link to corresponding `make_*` function.

**Comment by mccalluc** [comment]
Thought I had fixed it in 
- #1049

... but I was actually making changes to the generated python code, so it's been reverted. Reopen, and reimplement, but this time do it in Rust.

... and it would also be nice to add a CI check that would prevent this in the future. There's a comment at the top of the file, but it's easy to miss. Should be easy to just regenerate in CI and then check `git status`.
