### ISSUE TITLE
update make_count_by Python doc

### ISSUE THREAD

**Issue by SalilVadhan** [opendp/opendp#936]
The [Python doc ](https://docs.rs/opendp/latest/opendp/transformations/fn.make_count_by.html](https://docs.opendp.org/en/v0.3.0/api/python/opendp.trans.html#opendp.trans.make_count_by) says that the dataset size needs to be done, but that shouldn't be necessary and the [Rust doc](https://docs.rs/opendp/latest/opendp/transformations/fn.make_count_by.html) doesn't seem to require it.

**Comment by Shoeboxam** [comment]
This was because the docs version was 0.3.0. See #946 instead.
