### ISSUE TITLE
Investigate when Python constructors can do dtype coercion

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#943]
Now that dtypes are typically filled in via partial chaining, we may be able to relax the checks on certain int vs float arguments.

Integers can be coerced to floats, and sometimes floats can be coerced into integers.

**Comment by mccalluc** [comment]
@Shoeboxam -- Can you help me map out what this work entails? Are you envisioning more conversion happening in `py_to_c`, with a corresponding loosening of the checks in `check_similar_scalar`? Or would the work be done somewhere else?

**Comment by Shoeboxam** [comment]
@mccalluc Exactly. More work in py_to_c, as that function already has the expected dtype given to it.

**Comment by Shoeboxam** [comment]
Closed in #1509
