### ISSUE TITLE
Enable Google Search Console and/or Google Analytics

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#968]
Problem: We know little about how Google is indexing our pages, and how users are using our sites. “Search Console” (formerly “Webmaster Tools”) and “Google Analytics” are complementary. They pull information from different sources: for Search Console, we just need to demonstrate our ownership of a site; For analytics, we add JS to our pages, and so the browser is reporting back to Google directly.

For now, I think Search Console will be more than enough, and it is less invasive than Analytics.

From https://search.google.com/search-console/welcome:

Possible fix 1 (preferred):
- Someone with access to DNS for opendp.org can demonstrate that we own the domain, and all subdomains (ie, “docs”) 

Possible fix 2:
- Demonstrate that we own a domain or subdomain by adding a file at a particular URL. Going through a docs redeploy for this would probably be more of a nuisance than just demonstrating DNS ownership.

**Comment by raprasad** [comment]
Also explore analytics other than google that are more privacy focused
