### ISSUE TITLE
Use notebooks consistently in docs

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#971]
Prerequisite:
- #976 ... Are notebooks even the right direction?

Problem: Some examples use a doctest style instead of a notebook style. This style makes it a little harder for users to run it themselves (They can’t just use the notebook, and aren’t prompted to open in Binder), and it leads to making assertions rather than just showing the output, and it’s not possible to show any graphic output.

Incline towards making it all notebooks, but there are downsides: 
- Simple doctests no longer possible. 
- Need to decide what to replace the asserts with
- Diffs, etc, on notebook files can be more of a pain.

Some docs to switch; there may be others:
- https://docs.opendp.org/en/stable/user/combinators.html 
- https://docs.opendp.org/en/stable/user/programming-framework/supporting-elements.html

**Comment by Shoeboxam** [comment]
Can notebooks be branches in the tree? It might be the case that notebooks can only be leaf nodes.

**Comment by Shoeboxam** [comment]
Notebooks are also more difficult to:
* internationalize
* give code snips in multiple programming languages (like https://docs.h2o.ai/h2o/latest-stable/h2o-docs/cross-validation.html)

Might still be worth it (there may be solutions here), but should consider these tradeoffs before converting.

**Comment by mccalluc** [comment]
You're right: Notebooks are not the only or best solution, particularly if we'll want to present examples in multiple languages.
- Filed #1052

closing.
