### ISSUE TITLE
Simplify block diagram

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#979]
Problem: Some aspects of the architecture are not clear in the block diagram, and the hypothetical future projects make the diagram harder to read.

A revised diagram might highlight:
- What blocks belong to which repos
- What blocks constitute the OpenDP Commons
- New R interface
- DPCreator

It might leave out:
- Hypothetical projects
- FFI layer

**Comment by mccalluc** [comment]
Proposal:

[![diagram](https://docs.google.com/drawings/d/e/2PACX-1vTrq1N3dX2Z926blC_LFsaDudxGZZG99cpQu8yX1UFG7Vv_yISuKNUhl29QXzyTFXIwU_eCnHTrufes/pub?w=852&h=295)](https://docs.google.com/drawings/d/1lFEOmpAdnMOAZ7H6rXNdD833WnBFhpOj_C_8HM7TRFc/edit)

One substantive change: The current diagram suggests that SmartNoise depends directly on the Rust code, but glancing at the code, both SmartNoise packages are python. Am I confused?

**Comment by SalilVadhan** [comment]
I like the look of this diagram!  However, the OpenDP Commons should
include the OpenDP Library, but not SmartNoise.  It is more about community
ownership and governance rather than the nature of the software itself.

**Comment by mccalluc** [comment]
Thank you for clarification. We're mulling over displaying https://github.com/opendp/opendp-logger as a part of the commons. Not sure if there are other good examples.

**Comment by mccalluc** [comment]
Revised
- show that not everything in the org is in the commons
- emphasize that opendp library itself is in the commons
- move the "?" boxes outside entirely to suggest it is software that anyone can build on.

It feels less tidy than the first version, but more accurate.

![[v1](https://docs.google.com/drawings/d/1VRePWbnjlzAbW-fO4b9lvkjNkCzCGQRv3Z5-1j8LYCM/edit)](https://docs.google.com/drawings/d/e/2PACX-1vSDUceajUYQ_TRTQwSUUZAG_03nKy0kctQDVU6-jBJcHwWHKV_TbagZFfVWXxIpSQl4BsUYnkYwsQcR/pub?w=600)

**Comment by mccalluc** [comment]
The docs now on `main` (deployed on `nightly`) have made things more clear by just focusing on OpenDP the library (rather than OpenDP the project), so we no longer need a version of this diagram here. If it has a place in the project docs, that can be handled separately.
