### ISSUE TITLE
Friendlier 404s

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#986]
[This issue](https://github.com/opendp/opendp/issues/985) identifies a broken link from the project site to the docs site. What is currently shown is a default GitHub pages 404. I believe we can specify our own 404 page, and on it we might encourage users to use the site search.

**Comment by mccalluc** [comment]
I'm not entirely clear on the workflow here, but I was hoping the nightly build would have run last night, and the docs would be updated, but I'm not seeing the new 404 page, either as the default, or at this path: https://docs.opendp.org/en/nightly/404.html

Keep this issue open until something like https://docs.opendp.org/no-such-page returns our custom 404.

**Comment by raprasad** [comment]
@mccalluc: ^ The nightly build process needs an update to fix the Windows lib

**Comment by mccalluc** [comment]
With the docs release, the 404 page is in place: https://docs.opendp.org/bad-url ... but all assets are 404. Looking at one request:
```
<script src="_static/jquery.js"></script>
```


- New 404:
  - requests https://docs.opendp.org/_static/jquery.js: **404**
- https://docs.opendp.org --> https://docs.opendp.org/en/stable/index.html
  - requests https://docs.opendp.org/en/stable/_static/jquery.js: **200**

The 404 page needs to be at the top level to work for github, but that means the relative links for assets are broken. Options:

- See if sphinx multiversion has a special option for this (doubtful)
- Explicitly add all the assets as embedded html in rst (still making bad requests, hard to maintain)
- Meta tag redirect (Don't think that's possible from rst)
- Javascript redirect to `en/stable/404.html` (won't work for non-js clients, bad user experience.)
