### ISSUE TITLE
Notebook: Basic Data Analysis with the Context API

### ISSUE THREAD

**Issue by raprasad** [opendp/opendp#991]
Create a notebook similar to the “[Example Data Analysis](https://docs.opendp.org/en/stable/examples/pums-data-analysis.html)" notebook but using the Context API.

More details may be found here:
- https://docs.google.com/document/d/1Uvjfo5-qBmWvOdk60NhTqf1j077oD_WzcL9tx40U-rQ/edit

**Comment by mccalluc** [comment]
Draft notebook here: https://colab.research.google.com/drive/1kSTXlwpddSk4fS-9VpdAKA6QJmxFTdYs#scrollTo=ZZVVr85cjMms

**Comment by mccalluc** [comment]
We now have typical-workflow in the docs, which just works with a vector, and lots of polars examples as well. This can be closed.
