### ISSUE TITLE
Explain why you should choose OpenDP

### ISSUE THREAD

**Issue by mccalluc** [opendp/opendp#998]
There are multiple DP libraries out there. Near the top of the docs we should have a short argument for why someone should pick OpenDP, perhaps bullet points or a feature matrix. (And if other libraries do something well, acknowledge that, too! Having a presentation that is balanced can help people feel more confident that they've done their research.)

Some possible points:
- Under active development.
- Multiple language bindings give you the same functionality in the language of your choice.
- Rigorous development process (Rust backend, algorithm reviews) has produced a codebase that performs well in independent security audits (ie [Group and Attack: Auditing Differential Privacy](https://www.sri.inf.ethz.ch/publications/lokna2023groupandattack))
- Broad API supports a range of DP mechanisms
- (when Context API is out) Relatively easy to use

On the other side:
- OpenDP is agnostic about where the data is coming from. For any particular backend, there may be a library that provides some elements of DP with minimal changes to existing code.
  - https://pipelinedp.io/ -- "Provides a convenient API familiar to Spark or Beam developers"
  - [TensorFlow Privacy](https://www.tensorflow.org/responsible_ai/privacy/guide)
  - [Opacus for PyTorch](https://github.com/pytorch/opacus)
  - SQL integrations

Should also compare with:
- https://github.com/IBM/differential-privacy-library
- https://github.com/OpenMined/PyDP
  - Built on https://github.com/google/differential-privacy 

Please add to the list!

**Comment by SalilVadhan** [comment]
Backed by and (eventually) governed by the community (as opposed to a
single company)

-----
Salil Vadhan (he/they)

**Comment by mccalluc** [comment]
Before making the case for OpenDP, we should make the case for DP in general:
- See #317

**Comment by mccalluc** [comment]
The new docs on `main` cover this:

> ## Why OpenDP?
> 
> -    OpenDP is based on a [solid conceptual framework](https://projects.iq.harvard.edu/files/opendp/files/opendp_programming_framework_11may2020_1_01.pdf) for expressing privacy-aware computations.
> -    OpenDP is built on a Rust core for memory and thread safety and performance.
> -    OpenDP has a process for independent review of algorithms and implementations.
> -    OpenDP has performed well in [independent security audits](https://www.sri.inf.ethz.ch/publications/lokna2023groupandattack).
> -    OpenDP supports a range of differential privacy algorithms.
> -    OpenDP has bindings for Python and R, both built on the same Rust core for consistency and security.
> -    OpenDP is a community effort and is not owned or directed by a single corporation.
>
>  That said, OpenDP is not the best tool for every job. In particular, it is a fairly low-level interface: There are a number of other projects which try to make it easy to add differential privacy to existing SQL interfaces or ML frameworks. One such tool is [SmartNoise SDK](https://github.com/opendp/smartnoise-sdk), which is built on the OpenDP library.

Don't need to wait for release to close.
